### ISSUE TITLE
Homebridge skill only works when using debug mode.

### ISSUE THREAD

**Issue by Silentbob101** [NorthernMan54/homebridge-alexa#119]
If I run homebridge in debug mode (DEBUG=alexa* homebridge -I) the skill works and alexa can control my devices... if I run it normally i get this error

```
[Alexa] PowerController TurnOn 192.168.1.4 51826 undefined Error: Homebridge auth failed, invalid PIN 177-34-153
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaHAP.js:106:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by NorthernMan54** [comment]
This sounds like you are missing the -I option when you are running normally.

**Comment by Silentbob101** [comment]
Sorry for delay in replying... yep you were right! -I did the trick!
