### ISSUE TITLE
ECONNREFUSED error

### ISSUE THREAD

**Issue by jasehigh** [NorthernMan54/homebridge-alexa#126]
I run multiple home bridge instances on my Mac mini (one for each different smart device platform).

I have created a new homebred instance for Alexa with the following config.json:

```
{
	"bridge": {
		"name": "alexa",
		"username": "XX:XX:XX:XX:XX:XX",
		"port": 518XX,
		"pin": "031-45-XXX"
	},
	"platforms": [{
	    "platform": "Alexa",
    	    "name": "Alexa",
	    "username": “xxx”,
    	    "password": “xxx”
	}]
}
```

The username and password is as per that registered at [https://homebridge.cloudwatch.net](https://homebridge.cloudwatch.net)

This instance of homerbidge is run as a global deamon (with the -I option for insecure mode):

`/usr/local/bin/homebridge -I -U /Users/admin/.alexa`

The homebridge instance I want Alexa to see is using the [BroadlinkRM](https://github.com/lprhodes/homebridge-broadlink-rm) plugin. This is also running as a global deamon (with the -I option for insecure mode):

`/usr/local/bin/homebridge -I -U /Users/admin/.broadlink`

I can see that homebridge alexa is discovering the broadlnk homebridge server:

`alexaHAP Homebridge instance discovered Broadlink-7732 with 13 accessories +14ms`

and I can add the Alexa bridge to my homekit setup via the Home app.

However, I'm getting the following errors reported in the console:

```
  alexaLocal reconnect +3s
  alexaLocal error { Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
 code: 5 } +175ms
  alexaLocal reconnect +5s
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +93ms
```

Finally, I’ve added the home bridge skill to Alexa, linked using the username and passed registered at [https://homebridge.cloudwatch.net](https://homebridge.cloudwatch.net) and have asked Alexa to discover new smart home devices.

However, the accessories in my broadlink homebridge never show up in Alexa.

Any ideas where I’m going wrong would be much appreciated. I assume the errors above are the issue...

Jason.

**Comment by NorthernMan54** [comment]
The critical line in the log is this

alexaLocal error { Error: Connection refused: Not authorized


This is the plugin attempting to connect/login to the website server, and the login failing for some reason.  Please check your username and password.

**Comment by jasehigh** [comment]
Yep, that was it... many thanks for your help.

**Comment by Blurline** [comment]
>   alexaLocal error { Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:646:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12) code: 5 } +419ms
  alexaLocal reconnect +5s
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +157ms
  alexaLocal reconnect +5s


1. account https://homebridge.cloudwatch.net -> auth homebridge skill -> not working

 "bridge" : {
   "username" : "CC:22:3D:E3:CE:xx",
   "name" : "Alexa",
   "pin" : "031-45-1xx",
   "port" : 518XX
 },
 "platforms" : [
   {
     "username" : "xxx",
     "password" : "xxx",
     "name" : "Alexa",
     "platform" : "Alexa"
   },

2. Create second account https://homebridge.cloudwatch.net -> auth the new one (homebridge skill) -> not working

**Comment by NorthernMan54** [comment]
@Blurline I just changed my password to the wrong password and generated the same error.   The error is definitely either bad password or username.  Is there a possibility that you're using non-standard characters in your username or password and they are causing the issue?

**Comment by Blurline** [comment]
Create a new Account (3)

User/PW the same.

10 standard characters

**Comment by Blurline** [comment]
There ist a problem to disconnect the skill.

I tried with my second Echo Account

**Comment by NorthernMan54** [comment]
What is your new username?  Looking at the logging and I see 7 successful connections from Blurline, last at Sun Nov 04 2018 20:22:38 GMT

```

Blurline | Sun Nov 04 2018 18:42:41 GMT+0000 (UTC) | Sun Nov 04 2018 21:41:50 GMT+0000 (UTC) | 91 | Sun Nov 04 2018 20:22:38 GMT+0000 (UTC) | 7
-- | -- | -- | -- | -- | --

```

**Comment by Blurline** [comment]
Fixed. Double Config
/pi/

**Comment by NorthernMan54** [comment]
Tks good luck
