### ISSUE TITLE
not loading platform

### ISSUE THREAD

**Issue by djgalati** [NorthernMan54/homebridge-alexa#131]
Hello, I am unable to launch my homebridge with the current alexa npm for homebridge because for some reason, the homebridge wont load the alexa plugin from the config.json file. I've installed and updated all parts of the system, could someone please help.. Heres what I get in debug mode: 

`
pi@raspberrypi:/var/homebridge $ DEBUG=* homebridge -I
[10/20/2018, 1:23:46 PM] Loaded config.json with 12 accessories and 0 platforms.
[10/20/2018, 1:23:46 PM] ---
[10/20/2018, 1:23:50 PM] Loaded plugin: homebridge-alexa
[10/20/2018, 1:23:50 PM] Registering platform 'homebridge-alexa.Alexa'
[10/20/2018, 1:23:50 PM] ---
[10/20/2018, 1:23:50 PM] Loaded plugin: homebridge-cec-accessory
[10/20/2018, 1:23:50 PM] Registering accessory 'homebridge-cec.cec'
[10/20/2018, 1:23:50 PM] ---
[10/20/2018, 1:23:52 PM] Loaded plugin: homebridge-http-switch
[10/20/2018, 1:23:52 PM] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[10/20/2018, 1:23:52 PM] ---
[10/20/2018, 1:23:52 PM] Loaded plugin: homebridge-raspberrypi-temperature
[10/20/2018, 1:23:52 PM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[10/20/2018, 1:23:52 PM] ---
[10/20/2018, 1:23:53 PM] Loaded plugin: homebridge-weather
[10/20/2018, 1:23:54 PM] Registering accessory 'homebridge-weather.Weather'
[10/20/2018, 1:23:54 PM] ---
[10/20/2018, 1:23:54 PM] Loading 0 platforms...
[10/20/2018, 1:23:54 PM] Loading 12 accessories...
[10/20/2018, 1:23:54 PM] [TV Power] Initializing cec accessory...
[10/20/2018, 1:23:54 PM] [TV Power] Creating accessory service
[10/20/2018, 1:23:54 PM] [Homebridge CPU Temp] Initializing RaspberryPiTemperature accessory...
[10/20/2018, 1:23:54 PM] [TV Power 2] Initializing cec accessory...
[10/20/2018, 1:23:54 PM] [TV Power 2] Creating accessory service
[10/20/2018, 1:23:54 PM] [Outlet 1] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:23:54 PM] [Outlet 2 - Fridge] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:23:54 PM] [Outlet 3] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:23:54 PM] [Outlet 4] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:23:54 PM] [Current Temp] Initializing Weather accessory...
[10/20/2018, 1:23:54 PM] [Current Temp] Starting Polling background service for Current Temp
[10/20/2018, 1:23:54 PM] [Daily Max] Initializing Weather accessory...
[10/20/2018, 1:23:54 PM] [Daily Max] Starting Polling background service for Daily Max
[10/20/2018, 1:23:54 PM] [Daily Min] Initializing Weather accessory...
[10/20/2018, 1:23:54 PM] [Daily Min] Starting Polling background service for Daily Min
[10/20/2018, 1:23:54 PM] [Cloudiness] Initializing Weather accessory...
[10/20/2018, 1:23:54 PM] [Cloudiness] Starting Polling background service for Cloudiness
[10/20/2018, 1:23:54 PM] [Sun] Initializing Weather accessory...
[10/20/2018, 1:23:54 PM] [Sun] Starting Polling background service for Sun
Setup Payload:
X-HM://0023OA632L392
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 123-45-678 │
    └────────────┘

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:607:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:128:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:97:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
`
and here is my config.json file : 

{
   "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "123-45-678"
   },
   "description": "This is an example configuration for the Everything Homebridge plugin",
   "platforms":[
        {
                "platform": "Alexa",
                "name": "Alexa",
                "username": "****",
                "password": "****",
                "pin": "123-45-678"
        }
        ],
   "accessories": [
        {
                "accessory": "cec",
                "name": "TV Power",
                "type": "power",
                "address": 0
        },
        {
                "accessory": "RaspberryPiTemperature",
                "name": "Homebridge CPU Temp"
        },
        {
                "accessory": "HTTP-SWITCH",
                "name": "Outlet 1",
                "switchType": "stateful",
                "httpMethod": "GET",
                "onUrl": "http://192.168.0.125/R1/1",
                "offUrl": "http://192.168.0.125/R1/0",
                "statusUrl": "http://192.168.0.125/R1/S"
        },
        {
                "accessory": "HTTP-SWITCH",
                "name": "Outlet 2",
                "switchType": "stateful",
                "httpMethod": "GET",
                "onUrl": "http://192.168.0.125/R2/1",
                "offUrl": "http://192.168.0.125/R2/0",
                "statusUrl": "http://192.168.0.125/R2/S"
        },
        {
                "accessory": "HTTP-SWITCH",
                "name": "Outlet 3",
                "switchType": "stateful",
                "httpMethod": "GET",
                "onUrl": "http://192.168.0.125/R3/1",
                "offUrl": "http://192.168.0.125/R3/0",
                "statusUrl": "http://192.168.0.125/R3/S"
        },
        {
                "accessory": "HTTP-SWITCH",
                "name": "Outlet 4",
                "switchType": "stateful",
                "httpMethod": "GET",
                "onUrl": "http://192.168.0.125/R4/1",
                "offUrl": "http://192.168.0.125/R4/0",
                "statusUrl": "http://192.168.0.125/R4/S"
        },
        {
                "accessory": "Weather",
                "apikey": "488df9a4ac0ee51d36e98cf18bd9a091",
                "locationByCoordinates": "lat=35.1995&lon=-111.6515",
                "name": "Current Temp",
                "pollingInterval": 15,
                "unit": "imperial"
        },
        {
                "accessory": "Weather",
                "apikey": "488df9a4ac0ee51d36e98cf18bd9a091",
                "locationByCoordinates": "lat=35.1995&lon=-111.6515",
                "name": "Daily Max",
                "type": "max",
                "pollingInterval": 15,
                "unit": "imperial"
        },
        {
                "accessory": "Weather",
                "apikey": "488df9a4ac0ee51d36e98cf18bd9a091",
                "locationByCoordinates": "lat=35.1995&lon=-111.6515",
                "name": "Daily Min",
                "type": "min",
                "pollingInterval": 15,
                "unit": "imperial"
        },
        {
                "accessory": "Weather",
                "apikey": "488df9a4ac0ee51d36e98cf18bd9a091",
                "locationByCoordinates": "lat=35.1995&lon=-111.6515",
                "name": "Cloudiness",
                "type": "min",
                "pollingInterval": 15,
                "unit": "imperial",
                "nameHumidity": "Coverge"
        },
        {
                "accessory": "Weather",
                "apikey": "488df9a4ac0ee51d36e98cf18bd9a091",
                "locationByCoordinates": "lat=35.1995&lon=-111.6515",
                "name": "Sun",
                "type": "sun",
                "pollingInterval": 15,
                "unit": "imperial",
                "nameHumidity": "Sunniness"
        }
   ]
}

Any help with this would be much appreciated. P.S. ive already tried killall for the Error: listen EADDRINUSE :::51826 error but it still shows only while trying to debug alexa

**Comment by NorthernMan54** [comment]
If you have homebridge configured to start on boot with systemd or other startup methods, you need to disable start on boot, before attempting to debug

I use systemd on my RPI, so I use this command to stop the start on boot instance

sudo systemctl stop homebridge

This only stops homebridge from running in the background until your next reboot.

**Comment by djgalati** [comment]
Just ran that line and there's no change on output and the plugin is still not loaded

**Comment by djgalati** [comment]
Here is also my /etc/default/homebridge file:

# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to $
HOMEBRIDGE_OPTS=-I -U /var/homebridge

# If you uncomment the following line, homebridge will log more
# You can display this via systemd's journalctl: journalctl -f -u homebridge
 DEBUG=alexa* homebridge -I

**Comment by NorthernMan54** [comment]
DEBUG s/b

DEBUG=alexa*

**Comment by djgalati** [comment]
so should I remove homebridge -I from the file?

**Comment by NorthernMan54** [comment]
Yes, from that line

For example, mine looks like this

cat /etc/default/homebridge 
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
#HOMEBRIDGE_OPTS=-U /var/homebridge
HOMEBRIDGE_OPTS=-I

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
DEBUG=*

**Comment by djgalati** [comment]
attempted to try this the same as your (with and without "alexa") before the * in DEBUG=*, no changes.

**Comment by djgalati** [comment]
After a reboot the error message went away, it still does not show a loaded plugin when starting homebridge. here's what it says about alexa while launching

[10/20/2018, 1:51:36 PM] Loaded plugin: homebridge-alexa
[10/20/2018, 1:51:36 PM] Registering platform 'homebridge-alexa.Alexa'
[10/20/2018, 1:51:36 PM] ---

**Comment by NorthernMan54** [comment]
There should be significantly more logging during startup, can you include the full log file

**Comment by djgalati** [comment]
sorry to say but there was no logging change on this launch, even in debug mode

**Comment by djgalati** [comment]
pi@raspberrypi:/etc/default $ DEBUG=alexa* homebridge -I
[10/20/2018, 1:58:27 PM] Loaded config.json with 12 accessories and 0 platforms.
[10/20/2018, 1:58:27 PM] ---
[10/20/2018, 1:58:31 PM] Loaded plugin: homebridge-alexa
[10/20/2018, 1:58:31 PM] Registering platform 'homebridge-alexa.Alexa'
[10/20/2018, 1:58:31 PM] ---
[10/20/2018, 1:58:31 PM] Loaded plugin: homebridge-cec-accessory
[10/20/2018, 1:58:31 PM] Registering accessory 'homebridge-cec.cec'
[10/20/2018, 1:58:31 PM] ---
[10/20/2018, 1:58:33 PM] Loaded plugin: homebridge-http-switch
[10/20/2018, 1:58:33 PM] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[10/20/2018, 1:58:33 PM] ---
[10/20/2018, 1:58:33 PM] Loaded plugin: homebridge-raspberrypi-temperature
[10/20/2018, 1:58:33 PM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[10/20/2018, 1:58:33 PM] ---
[10/20/2018, 1:58:34 PM] Loaded plugin: homebridge-weather
[10/20/2018, 1:58:35 PM] Registering accessory 'homebridge-weather.Weather'
[10/20/2018, 1:58:35 PM] ---
[10/20/2018, 1:58:35 PM] Loading 0 platforms...
[10/20/2018, 1:58:35 PM] Loading 12 accessories...
[10/20/2018, 1:58:35 PM] [TV Power] Initializing cec accessory...
[10/20/2018, 1:58:35 PM] [TV Power] Creating accessory service
[10/20/2018, 1:58:35 PM] [Homebridge CPU Temp] Initializing RaspberryPiTemperature accessory...
[10/20/2018, 1:58:35 PM] [TV Power 2] Initializing cec accessory...
[10/20/2018, 1:58:35 PM] [TV Power 2] Creating accessory service
[10/20/2018, 1:58:35 PM] [Outlet 1] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:58:35 PM] [Outlet 2 - Fridge] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:58:35 PM] [Outlet 3] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:58:35 PM] [Outlet 4] Initializing HTTP-SWITCH accessory...
[10/20/2018, 1:58:35 PM] [Current Temp] Initializing Weather accessory...
[10/20/2018, 1:58:35 PM] [Current Temp] Starting Polling background service for Current Temp
[10/20/2018, 1:58:35 PM] [Daily Max] Initializing Weather accessory...
[10/20/2018, 1:58:35 PM] [Daily Max] Starting Polling background service for Daily Max
[10/20/2018, 1:58:35 PM] [Daily Min] Initializing Weather accessory...
[10/20/2018, 1:58:35 PM] [Daily Min] Starting Polling background service for Daily Min
[10/20/2018, 1:58:35 PM] [Cloudiness] Initializing Weather accessory...
[10/20/2018, 1:58:35 PM] [Cloudiness] Starting Polling background service for Cloudiness
[10/20/2018, 1:58:35 PM] [Sun] Initializing Weather accessory...
[10/20/2018, 1:58:35 PM] [Sun] Starting Polling background service for Sun
Setup Payload:
X-HM://0023OA632L392
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:



























Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 123-45-678 │
    └────────────┘

[10/20/2018, 1:58:36 PM] Homebridge is running on port 51826.

**Comment by NorthernMan54** [comment]
Sorry, try

DEBUG=* homebridge -I

**Comment by djgalati** [comment]
pi@raspberrypi:/etc/default $ DEBUG=* homebridge -I
[10/20/2018, 2:00:40 PM] Loaded config.json with 12 accessories and 0 platforms.
[10/20/2018, 2:00:40 PM] ---
[10/20/2018, 2:00:45 PM] Loaded plugin: homebridge-alexa
[10/20/2018, 2:00:45 PM] Registering platform 'homebridge-alexa.Alexa'
[10/20/2018, 2:00:45 PM] ---
[10/20/2018, 2:00:45 PM] Loaded plugin: homebridge-cec-accessory
[10/20/2018, 2:00:45 PM] Registering accessory 'homebridge-cec.cec'
[10/20/2018, 2:00:45 PM] ---
[10/20/2018, 2:00:46 PM] Loaded plugin: homebridge-http-switch
[10/20/2018, 2:00:46 PM] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[10/20/2018, 2:00:46 PM] ---
[10/20/2018, 2:00:46 PM] Loaded plugin: homebridge-raspberrypi-temperature
[10/20/2018, 2:00:46 PM] Registering accessory 'homebridge-raspberrypi-temperature.RaspberryPiTemperature'
[10/20/2018, 2:00:46 PM] ---
[10/20/2018, 2:00:47 PM] Loaded plugin: homebridge-weather
[10/20/2018, 2:00:49 PM] Registering accessory 'homebridge-weather.Weather'
[10/20/2018, 2:00:49 PM] ---
[10/20/2018, 2:00:49 PM] Loading 0 platforms...
[10/20/2018, 2:00:49 PM] Loading 12 accessories...
[10/20/2018, 2:00:49 PM] [TV Power] Initializing cec accessory...
[10/20/2018, 2:00:49 PM] [TV Power] Creating accessory service
[10/20/2018, 2:00:49 PM] [Homebridge CPU Temp] Initializing RaspberryPiTemperature accessory...
[10/20/2018, 2:00:49 PM] [TV Power 2] Initializing cec accessory...
[10/20/2018, 2:00:49 PM] [TV Power 2] Creating accessory service
[10/20/2018, 2:00:49 PM] [Outlet 1] Initializing HTTP-SWITCH accessory...
[10/20/2018, 2:00:49 PM] [Outlet 2 - Fridge] Initializing HTTP-SWITCH accessory...
[10/20/2018, 2:00:49 PM] [Outlet 3] Initializing HTTP-SWITCH accessory...
[10/20/2018, 2:00:49 PM] [Outlet 4] Initializing HTTP-SWITCH accessory...
[10/20/2018, 2:00:49 PM] [Current Temp] Initializing Weather accessory...
[10/20/2018, 2:00:49 PM] [Current Temp] Starting Polling background service for Current Temp
[10/20/2018, 2:00:49 PM] [Daily Max] Initializing Weather accessory...
[10/20/2018, 2:00:49 PM] [Daily Max] Starting Polling background service for Daily Max
[10/20/2018, 2:00:49 PM] [Daily Min] Initializing Weather accessory...
[10/20/2018, 2:00:49 PM] [Daily Min] Starting Polling background service for Daily Min
[10/20/2018, 2:00:49 PM] [Cloudiness] Initializing Weather accessory...
[10/20/2018, 2:00:49 PM] [Cloudiness] Starting Polling background service for Cloudiness
[10/20/2018, 2:00:49 PM] [Sun] Initializing Weather accessory...
[10/20/2018, 2:00:49 PM] [Sun] Starting Polling background service for Sun
Setup Payload:
X-HM://0023OA632L392
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:



























Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 123-45-678 │
    └────────────┘

  EventedHTTPServer Server listening on port 51826 +0ms
[10/20/2018, 2:00:49 PM] Homebridge is running on port 51826

This worked but I believe since the platform is not being loaded in the config.json file, The alexa was not able to discover any devices

**Comment by djgalati** [comment]
Is there a reason the config.json file would let the pi run if I have the platform code in the file and it launched without errors

**Comment by NorthernMan54** [comment]
Just comparing your log to mine, and I see messages which are suspicious

Yours

[10/20/2018, 2:00:40 PM] Loaded config.json with 12 accessories and 0 platforms.

Mine

[2018-10-20 15:08:54] Loaded config.json with 0 accessories and 2 platforms.

In my config I have 2 platform plugins and no accessories

I'm wondering if your system has 2 config.json files, in 2 separate locations

**Comment by djgalati** [comment]
you were right, I had the wrong config.json file. Thank you so much for all of your help!

**Comment by NorthernMan54** [comment]
Good luck
