### ISSUE TITLE
Authentication failing with same pin configration on docker-homebridge running on raspberry pi

### ISSUE THREAD

**Issue by sukkola** [NorthernMan54/homebridge-alexa#144]
{
    "bridge": {
        "name": "Homebridge",
...
        "port": 51826,
        "pin": "123123123"
...
        {
            "platform": "Alexa",
            "name": "Alexa",
...
            "pin": "123123123"
        }
    ]
}

----------------------------
[11/18/2018, 9:00:56 PM] [Alexa] PowerController TurnOn xxx.xxx.xxx.xxx port undefined Error: Homebridge auth failed, invalid PIN 123123123
    at Request.<anonymous> (/homebridge/node_modules/homebridge-alexa/lib/alexaHAP.js:106:18)
    at Request._callback (/homebridge/node_modules/lodash/lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (/homebridge/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/homebridge/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/homebridge/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/homebridge/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/request/request.js:1083:12)

**Comment by sukkola** [comment]
configuration was missing the homebridge unsecure flag on the docker container
