### ISSUE TITLE
confusion on setup

### ISSUE THREAD

**Issue by mreassassin** [NorthernMan54/homebridge-alexa#147]
I went through all of the steps but I'm not getting any of my homebridge devices showing up in my alexa app.  I'm only using the app on my phone.  i just ordered an echo today and was hoping to have everything setup for when it comes in.  I'm constantly getting:

[Alexa] ERROR: HAP Discovery failed, please review config

i am using the -I when running homebridge.  only running one instance.  I have a bunch of thing running through homebridge (xbox, light/fan switches, directv, etc.)  Do i need to wait until I get the echo for it to be able to discover all of the devices (I'm wondering if I'm reading that right in the troubleshooting)?

any help is appreciated.

thanks!

**Comment by NorthernMan54** [comment]
The error message is due to a missing config step, please review your setup.  Also when you don’t have an actual Alexa yet, you need to use one of the software based Alexa’s like the reverb app to simulate an Alexa.

**Comment by mreassassin** [comment]
Do I need to call out each individual device that’s running through homebridge?  Like TVs, lights, speakers, outlets, garage, locks etc?  Or is there something I’m missing in the homebridge skill within Alexa?  I’m not seeing any options there. All I see is manage smart home devices but it doesn’t show any of my already running plugins and devices from homebridge...

**Comment by mreassassin** [comment]
I’ve also tried reverb. It says noting to discover and tells me to enable smart home skill in Alexa. Any ideas?

**Comment by NorthernMan54** [comment]
Can you share a DEBUG log and include you asking Alexa to discover devices.  As the service has been pretty stable I expect there to be a setup issue somewhere.  Have you linked the skill to your amazon account?

**Comment by mreassassin** [comment]
> pi@raspberrypi:~ $ DEBUG=alexa* homebridge -I
[2018-11-27 11:27:48] Loaded config.json with 2 accessories and 5 platforms.
[2018-11-27 11:27:48] ---
[2018-11-27 11:27:50] Loaded plugin: homebridge-alexa
[2018-11-27 11:27:50] Registering platform 'homebridge-alexa.Alexa'
[2018-11-27 11:27:50] ---
[2018-11-27 11:27:50] Loaded plugin: homebridge-chamberlain
[2018-11-27 11:27:50] Registering accessory 'homebridge-chamberlain.Chamberlain'
[2018-11-27 11:27:50] ---
[2018-11-27 11:27:50] Loaded plugin: homebridge-cmdswitch2
[2018-11-27 11:27:50] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[2018-11-27 11:27:50] ---
[2018-11-27 11:27:50] Loaded plugin: homebridge-denon
[2018-11-27 11:27:50] Registering accessory 'homebridge-denon-marantz-avr.DenonMarantzAVR'
[2018-11-27 11:27:50] ---
[2018-11-27 11:27:50] Loaded plugin: homebridge-directv
[2018-11-27 11:27:50] Registering accessory 'homebridge-directv-location.DirectvSTB'
[2018-11-27 11:27:50] Registering platform 'homebridge-directv.Directv'
[2018-11-27 11:27:50] ---
[2018-11-27 11:27:51] Loaded plugin: homebridge-homeassistant
[2018-11-27 11:27:51] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-11-27 11:27:51] ---
[2018-11-27 11:27:51] Loaded plugin: homebridge-marantz-volume
[2018-11-27 11:27:51] Registering accessory 'homebridge-marantz-volume.marantz-volume'
[2018-11-27 11:27:51] ---
[2018-11-27 11:27:51] Loaded plugin: homebridge-samsung-tizen
[2018-11-27 11:27:51] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[2018-11-27 11:27:51] ---
[2018-11-27 11:27:52] Loaded plugin: homebridge-ssh
[2018-11-27 11:27:52] Registering accessory 'homebridge-ssh.SSH'
[2018-11-27 11:27:52] ---
[2018-11-27 11:27:54] Loaded plugin: homebridge-wink3
[2018-11-27 11:27:54] Registering platform 'homebridge-wink.Wink'
[2018-11-27 11:27:54] ---
[2018-11-27 11:27:54] Loaded plugin: homebridge-wol
[2018-11-27 11:27:54] Registering accessory 'homebridge-wol.NetworkDevice'
[2018-11-27 11:27:54] ---
[2018-11-27 11:27:54] Loaded plugin: homebridge-xbox-one
[2018-11-27 11:27:54] Registering accessory 'homebridge-xbox-one.Xbox'
[2018-11-27 11:27:54] ---
[2018-11-27 11:27:54] Loading 5 platforms...
[2018-11-27 11:27:54] [Wink] Initializing Wink platform...
[2018-11-27 11:27:54] [DTV] Initializing Directv platform...
[2018-11-27 11:27:54] [DTV] Fetching DTV locations.
[2018-11-27 11:27:54] [CMD Switch] Initializing cmdSwitch2 platform...
[2018-11-27 11:27:54] [SamsungTizen] Initializing SamsungTizen platform...
[2018-11-27 11:27:54] [SamsungTizen] Initializing platform accessory 'Living Room TV'...
[2018-11-27 11:27:54] [SamsungTizen] Initializing platform accessory 'Goto PS4 Living Room TV'...
[2018-11-27 11:27:54] [SamsungTizen] Initializing platform accessory 'Goto XBOX Living Room TV'...
[2018-11-27 11:27:54] [SamsungTizen] Initializing platform accessory 'Turn Off the TV Living Room TV'...
[2018-11-27 11:27:54] [Alexa] Initializing Alexa platform...
[2018-11-27 11:27:54] Loading 2 accessories...
[2018-11-27 11:27:54] [Living Room Volume] Initializing marantz-volume accessory...
[2018-11-27 11:27:54] [Garage Door] Initializing Chamberlain accessory...
[2018-11-27 11:27:54] [Wink] Loaded from cache: Kitchen Outlet (binary_switch/675469)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Mar Window Sensor (sensor_pod/456393)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Garage Entry Motion Sensor (sensor_pod/456401)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Upstairs Plug (binary_switch/675549)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Master Window Sensor (sensor_pod/456465)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Perez Home Downstairs Thermostat (thermostat/297687)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Perez Home Upstairs Thermostat (thermostat/298145)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Side Garage (binary_switch/716697)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Front Door (door_bell/72673)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Garage Entry (binary_switch/772237)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Front House (binary_switch/772250)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Front Porch (binary_switch/772259)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Our Room (binary_switch/781423)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Kitchen (binary_switch/793127)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Living Room Fan (binary_switch/819446)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Dining Room (binary_switch/848740)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Family Room (binary_switch/848831)
[2018-11-27 11:27:54] [Wink] Loaded from cache: Living Room (binary_switch/867841)
[2018-11-27 11:27:54] [CMD Switch] Initializing platform accessory 'PS4'...
[2018-11-27 11:27:54] [CMD Switch] Initializing platform accessory 'XBOX'...
[2018-11-27 11:27:54] [CMD Switch] Initializing platform accessory 'Garage XBOX'...
[2018-11-27 11:27:54] [CMD Switch] Initializing platform accessory 'Bedroom XBOX'...
  alexaHAP Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +9ms
[2018-11-27 11:27:54] [Wink] Refreshing devices...
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +405ms
  alexaLocal offline +11ms
[2018-11-27 11:27:55] [DTV] Finding DTV Locations (accessories)...
[2018-11-27 11:27:55] [DTV] Found DTV Location CAVE
[2018-11-27 11:27:55] [DTV] Found DTV Location BEDROOM
[2018-11-27 11:27:55] [DTV] Found DTV Location MAIN
[2018-11-27 11:27:55] [DTV] Initializing platform accessory 'Cave DTV'...
[2018-11-27 11:27:55] [DTV] Initializing platform accessory 'Bedroom DTV'...
[2018-11-27 11:27:55] [DTV] Initializing platform accessory 'Main DTV'...
Setup Payload:
X-HM://0023ISYWYNDHL
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:



























Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-1XX │
    └────────────┘

[2018-11-27 11:27:55] Homebridge is running on port 518XX.
[2018-11-27 11:27:56] [Garage Door] doorstate changed from closed to open
[2018-11-27 11:27:56] [Garage Door] desireddoorstate changed from closed to open
[2018-11-27 11:27:57] [Wink] Hidden by hide_groups config option: Lock (lock/255995)
[2018-11-27 11:27:57] [Wink] Hidden by hide_groups config option: Garage Door (garage_door/146942)
[2018-11-27 11:27:57] [Wink] Devices refreshed
[2018-11-27 11:27:57] [Wink] Checking if hub is reachable (MarHub, 192.168.1.197)...
[2018-11-27 11:27:58] [Wink] Hub is reachable locally (MarHub, 192.168.1.197)
[2018-11-27 11:27:58] [Wink] Authenticated with local hub (MarHub, 192.168.1.197)
  alexaLocal reconnect +5s
  alexaLocal connect command/mreassassin/# +218ms
  alexaHAP Starting Homebridge instance discovery +9s
  alexaHAP Starting Homebridge instance discovery +15s
  alexaLocal Emitting Alexa.Discovery +13s
[2018-11-27 11:28:37] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaHAP Starting Homebridge instance discovery +2s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
[2018-11-27 11:29:28] [Wink] Received update notification: Garage Entry (binary_switch/772237)
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaLocal Emitting Alexa.Discovery +3s
[2018-11-27 11:35:28] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaHAP Ending Homebridge instance discovery +7s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaLocal Emitting Alexa.Discovery +1s
[2018-11-27 11:36:40] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaHAP Ending Homebridge instance discovery +9s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
[2018-11-27 11:37:29] [Wink] Received update notification: Garage Entry Motion Sensor (sensor_pod/456401)
  alexaHAP Ending Homebridge instance discovery +10s
  alexaHAP Starting Homebridge instance discovery +5s
  alexaHAP Ending Homebridge instance discovery +10s
^C[2018-11-27 11:37:50] Got SIGINT, shutting down Homebridge...
  alexaHAP Starting Homebridge instance discovery +5s

> 

I did link the skill to my amazon account.

**Comment by mreassassin** [comment]
i think i linked my skill to my homebridge-alexa account that i had to create...  is that wrong?

**Comment by mreassassin** [comment]
heres my config:

> 

		{
	    "platform": "Alexa",
	    "name": "Alexa",
	    "username": "xxxxxxxxxxx",
	    "password": "xxxxxxx",
	    "pin": "031-45-1XX",
	    "refresh": 15
	  }

>

**Comment by NorthernMan54** [comment]
What type of environment are you running homebridge on?  The plugin is failing mdns discover of homebridge.  I’m wondering if a firewall is blocking the mdns traffic.

**Comment by mreassassin** [comment]
how can I find out?  I'm running on a rasperry pi.  rasberian lite, i believe.

**Comment by NorthernMan54** [comment]
This error message does indicate one good thing, the connection to Alexa is working okay, and the Alexa Discover Devices message is being received by the plugin.

```
alexaLocal Emitting Alexa.Discovery +3s
[2018-11-27 11:35:28] [Alexa] ERROR: HAP Discovery failed, please review config
```

The error is just indicating that no local devices where found.  With your raspberrypi, how is it connected to the network, hard wired or via wireless?  If it is connected via wireless, is it possible to try a wired connection?

**Comment by mreassassin** [comment]
wired...

**Comment by mreassassin** [comment]
in case this helps:

pi@raspberrypi:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.234  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a5f2:1129:760c:8112  prefixlen 64  scopeid 0x20<link>
        inet6 2605:e000:1705:953:444c:6407:b21c:f1bf  prefixlen 64  scopeid 0x0<global>
        ether b8:27:eb:0c:6c:b5  txqueuelen 1000  (Ethernet)
        RX packets 10557  bytes 2885917 (2.7 MiB)
        RX errors 0  dropped 8  overruns 0  frame 0
        TX packets 9399  bytes 2144843 (2.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 754  bytes 415064 (405.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 754  bytes 415064 (405.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.28  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::3f33:5a2e:7cf4:29a3  prefixlen 64  scopeid 0x20<link>
        inet6 2605:e000:1705:953:3059:1c90:10c0:e878  prefixlen 64  scopeid 0x0<global>
        ether b8:27:eb:59:39:e0  txqueuelen 1000  (Ethernet)
        RX packets 2608  bytes 739199 (721.8 KiB)
        RX errors 0  dropped 6  overruns 0  frame 0
        TX packets 94  bytes 14185 (13.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by mreassassin** [comment]
fresh install of raspbian and I reinstalled homebridge and plugins.  worked like a charm!
