### ISSUE TITLE
Crashing when activating Echo

### ISSUE THREAD

**Issue by samsonrosen** [NorthernMan54/homebridge-alexa#15]
Hi! This has been working great. I had to delete the plugin-persist folder as I had my iPhone replaced and home kit wouldn't be discovered etc.

Since then, whenever I used my Echo Dot it causes home bridge to crash.

```
Church-Server:~ churchserver$ sudo DEBUG=* homebridge
Password:
Sorry, try again.
Password:
[21/06/2017, 18:50:25] Loaded plugin: homebridge-amazondash
[21/06/2017, 18:50:25] Registering platform 'homebridge-amazondash.AmazonDash'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-broadlink-rm
[21/06/2017, 18:50:25] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-cmdswitch2
[21/06/2017, 18:50:25] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-dash
[21/06/2017, 18:50:25] Registering accessory 'homebridge-dash.Dash'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-milight
[21/06/2017, 18:50:25] Registering platform 'homebridge-milight.MiLight'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-people
[21/06/2017, 18:50:25] Registering platform 'homebridge-people.People'
[21/06/2017, 18:50:25] Registering accessory 'homebridge-people.PeopleAccessory'
[21/06/2017, 18:50:25] Registering accessory 'homebridge-people.PeopleAllAccessory'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-platform-wemo
[21/06/2017, 18:50:25] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded plugin: homebridge-statefuldummy
[21/06/2017, 18:50:25] Registering accessory 'homebridge-statefuldummy.StatefulDummySwitch'
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loaded config.json with 0 accessories and 6 platforms.
[21/06/2017, 18:50:25] ---
[21/06/2017, 18:50:25] Loading 6 platforms...
[21/06/2017, 18:50:25] Initializing People platform...
[21/06/2017, 18:50:25] Initializing platform accessory 'Sam'...
[21/06/2017, 18:50:25] Initializing platform accessory 'Stuart'...
[21/06/2017, 18:50:25] Initializing platform accessory 'Kit'...
[21/06/2017, 18:50:25] Initializing platform accessory 'Laurence'...
[21/06/2017, 18:50:25] Initializing platform accessory 'Anyone'...
[21/06/2017, 18:50:25] Initializing platform accessory 'No One'...
[21/06/2017, 18:50:25] WebHook: Started server on port '51828'.
[21/06/2017, 18:50:25] Initializing cmdSwitch2 platform...
[21/06/2017, 18:50:25] [MiLight] Initializing MiLight platform...
[21/06/2017, 18:50:25] [MiLight] Initializing platform accessory 'Light'...
[21/06/2017, 18:50:25] [MiLight] Initializing platform accessory 'Lamp'...
[21/06/2017, 18:50:25] [WeMo Platform] Initializing BelkinWeMo platform...
[21/06/2017, 18:50:25] Initializing AmazonDash platform...
[21/06/2017, 18:50:25] [Broadlink RM] Initializing BroadlinkRM platform...
[21/06/2017, 18:50:25] [Broadlink RM] Initializing platform accessory 'Learn'...
[21/06/2017, 18:50:25] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
[21/06/2017, 18:50:25] [Broadlink RM] Initializing platform accessory 'Apple TV'...
[21/06/2017, 18:50:25] [Broadlink RM] Initializing platform accessory 'TV'...
[21/06/2017, 18:50:25] [Broadlink RM] Initializing platform accessory 'Amp'...
[21/06/2017, 18:50:25] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  ssdp not running +0ms
[21/06/2017, 18:50:25] Initializing platform accessory 'Kettle'...
  EventedHTTPServer Server listening on port 51826 +20ms
[21/06/2017, 18:50:25] Homebridge is running on port 51826.
  ssdp binding to port 1900 for ssdp discovery +6ms
  node-ssdp:client SSDP listening: { address: 'http://0.0.0.0:51830' } +0ms
  node-ssdp:client Sending an M-SEARCH request +5ms
  ssdp server listening 0.0.0.0:1900 192.168.1.69 +9ms
  node-ssdp:client Sent M-SEARCH request: { message: 'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:Belkin:service:basicevent:1\r\nMAN: "ssdp:discover"\r\nMX: 3\r\n\r\n' } +3ms
Discovered Broadlink RM device at 192.168.1.204 (0d:43:b4:fb:fd:a5)
  EventedHTTPServer [::ffff:192.168.1.136] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.1.136] HTTP server listening on port 49937 +1ms
  EventedHTTPServer [::ffff:192.168.1.136] HTTP request: /pair-verify +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  EventedHTTPServer [::ffff:192.168.1.136] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:192.168.1.136] Client connection closed +7ms
  EventedHTTPServer [::ffff:192.168.1.136] HTTP connection was closed +1ms
  EventedHTTPServer [::ffff:192.168.1.136] HTTP server was closed +1ms
[21/06/2017, 18:50:27] [Broadlink RM] Apple TV setSwitchState: 0
[21/06/2017, 18:50:27] [Broadlink RM] Apple TV setSwitchState: already 0
[21/06/2017, 18:50:27] [Broadlink RM] TV setSwitchState: 0
[21/06/2017, 18:50:27] [Broadlink RM] TV setSwitchState: already 0
[21/06/2017, 18:50:27] [Broadlink RM] Amp setSwitchState: 0
[21/06/2017, 18:50:27] [Broadlink RM] Amp setSwitchState: already 0
  EventedHTTPServer [::ffff:192.168.1.70] New connection from client +3s
  EventedHTTPServer [::ffff:192.168.1.70] HTTP server listening on port 49939 +1ms
  EventedHTTPServer [::ffff:192.168.1.70] HTTP request: /pair-verify +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  EventedHTTPServer [::ffff:192.168.1.70] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.1.70] Client connection closed +6ms
  EventedHTTPServer [::ffff:192.168.1.70] HTTP connection was closed +0ms
  EventedHTTPServer [::ffff:192.168.1.70] HTTP server was closed +0ms
  EventedHTTPServer [::ffff:192.168.1.195] New connection from client +2s
  EventedHTTPServer [::ffff:192.168.1.195] HTTP server listening on port 49941 +0ms
  EventedHTTPServer [::ffff:192.168.1.195] HTTP request: /api/fAIXoVTmZhhQRhoIU8S3gNoZ5QCDDd1CjODo8MpD/lights/101/state +3ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /api/fAIXoVTmZhhQRhoIU8S3gNoZ5QCDDd1CjODo8MpD/lights/101/state +0ms
  hue hueDevices not cached {} 101 +2ms
  hue Name Homebridge 0000003E-0000-1000-8000-0026BB765291 +7ms
  hue Name Sam 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Stuart 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Kit 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Laurence 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Anyone 0000003E-0000-1000-8000-0026BB765291 +1ms
  hue Name No One 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Light 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Light 00000043-0000-1000-8000-0026BB765291 +0ms
  hue device response 8 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Light',
  modelid: 'LWB004',
  manufacturername: 'MiLight',
  uniqueid: 'cc:22:3d:e3:ce:30:08:09-10',
  swversion: '66012040' } +0ms
  hue Name Lamp 0000003E-0000-1000-8000-0026BB765291 +1ms
  hue Name Lamp 00000043-0000-1000-8000-0026BB765291 +1ms
  hue device response 9 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Lamp',
  modelid: 'LWB004',
  manufacturername: 'MiLight',
  uniqueid: 'cc:22:3d:e3:ce:30:09:09-10',
  swversion: '66012040' } +0ms
  hue Name Learn 0000003E-0000-1000-8000-0026BB765291 +1ms
  hue Name Learn 00000049-0000-1000-8000-0026BB765291 +0ms
  hue device response 10 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Learn',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:10:09-00',
  swversion: '66012040' } +0ms
  hue Name Scan Frequency 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Scan Frequency 00000049-0000-1000-8000-0026BB765291 +0ms
  hue device response 11 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Scan Frequency',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:11:09-00',
  swversion: '66012040' } +0ms
  hue Name Apple TV 0000003E-0000-1000-8000-0026BB765291 +1ms
  hue Name Apple TV 00000049-0000-1000-8000-0026BB765291 +0ms
  hue device response 12 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Apple TV',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:12:09-00',
  swversion: '66012040' } +0ms
  hue Name TV 0000003E-0000-1000-8000-0026BB765291 +1ms
  hue Name TV 00000049-0000-1000-8000-0026BB765291 +0ms
  hue device response 13 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'TV',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:13:09-00',
  swversion: '66012040' } +0ms
  hue Name Amp 0000003E-0000-1000-8000-0026BB765291 +1ms
  hue Name Amp 00000049-0000-1000-8000-0026BB765291 +0ms
  hue device response 14 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Amp',
  modelid: 'LWB004',
  manufacturername: 'Broadlink',
  uniqueid: 'cc:22:3d:e3:ce:30:14:09-00',
  swversion: '66012040' } +0ms
  hue Name Kettle 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name Kettle 00000049-0000-1000-8000-0026BB765291 +0ms
  hue device response 15 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'Kettle',
  modelid: 'LWB004',
  manufacturername: 'Default-Manufacturer',
  uniqueid: 'cc:22:3d:e3:ce:30:15:09-00',
  swversion: '66012040' } +0ms
  hue Name Bedroom Light Switch 0000003E-0000-1000-8000-0026BB765291 +2ms
  hue Name WeMo Switch 0000003E-0000-1000-8000-0026BB765291 +0ms
  hue Name WeMo Switch 00000047-0000-1000-8000-0026BB765291 +0ms
  hue device response 17 { state: 
   { on: false,
     bri: 0,
     hue: 0,
     sat: 0,
     effect: 'none',
     ct: 0,
     alert: 'none',
     reachable: true },
  type: 'Dimmable light',
  name: 'WeMo Switch',
  modelid: 'LWB004',
  manufacturername: 'Belkin WeMo',
  uniqueid: 'cc:22:3d:e3:ce:30:17:10-00',
  swversion: '66012040' } +0ms
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:384
    var mac = hueDevices[lightid].uniqueid.split(':');
                                 ^

TypeError: Cannot read property 'uniqueid' of undefined
    at _getOiid (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:384:34)
    at hueToHKCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:199:24)
    at Object.handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:88:24)
    at HAPServer._handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:923:7)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:220:47)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by samsonrosen** [comment]
I was being an idiot - I forgot to rescan after I re-setup homebridge, so it was cause it to crash.
