### ISSUE TITLE
getting errors don't exactly know why, new to this plugin

### ISSUE THREAD

**Issue by roberkane212** [NorthernMan54/homebridge-alexa#162]
Getting errors can't get this plugin to work, ran DEBUG and got

 alexaHAP Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +5ms
[2019-1-5 04:01:34] [CMD Switch] Initializing platform accessory 'PS4'...
[2019-1-5 04:01:34] [CMD Switch] Initializing platform accessory 'Grand Theft Auto SA'...
[2019-1-5 04:01:34] [CMD Switch] Initializing platform accessory 'Dragonball FighterZ'...
[2019-1-5 04:01:34] [CMD Switch] Initializing platform accessory 'Grand Theft Auto VC'...
[2019-1-5 04:01:34] [CMD Switch] Initializing platform accessory 'Grand Theft Auto 3'...
[2019-1-5 04:01:34] Homebridge is running on port 51826.
[2019-1-5 04:01:34] [Broadlink RM] Cable On/Off getSwitchState: false
[2019-1-5 04:01:34] [Broadlink RM] Cable Guide getSwitchState: false
[2019-1-5 04:01:34] [Broadlink RM] Cable Select/OK getSwitchState: false
[2019-1-5 04:01:34] [Broadlink RM] Cable Exit getSwitchState: false
[2019-1-5 04:01:34] [Broadlink RM] Cable Info getSwitchState: false
[2019-1-5 04:01:34] [Broadlink RM] TV On/Off getSwitchState: false
  alexaHAP HAP Device discovered iHome SmartPlug-29CB53 [ '192.168.0.3', 'fe80::429f:38ff:fe29:cb53' ] +716ms
  alexaHAP HAP instance address: iHome SmartPlug-29CB53 -> hap-29CB53.local -> 192.168.0.3 +19ms
  alexaHAP HAP Device discovered iHome SmartPlug-8DB6D3 [ '192.168.0.4',
  'fe80::82a5:89ff:fe8d:b6d3',
  '::82a5:89ff:fe8d:b6d3' ] +106ms
  alexaHAP HAP instance address: iHome SmartPlug-8DB6D3 -> hap-8DB6D3.local -> 192.168.0.4 +12ms
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +174ms
  alexaLocal offline +39ms
  alexaHAP HAP Discover failed iHome SmartPlug-29CB53 http://192.168.0.3:80 error code 470 +77ms
  alexaHAP HAP Discover failed iHome SmartPlug-8DB6D3 http://192.168.0.4:80 error code 470 +25ms
[2019-1-5 04:01:35] [Broadlink RM] 
[2019-1-5 04:01:35] [Broadlink RM] **************************************************************************************************************
[2019-1-5 04:01:35] [Broadlink RM] ** Welcome to version 3.5.5 of the Homebridge Broadlink RM Plugin!
[2019-1-5 04:01:35] [Broadlink RM] ** 
[2019-1-5 04:01:35] [Broadlink RM] ** Find out what's in the latest release here: https://github.com/lprhodes/homebridge-broadlink-rm/releases
[2019-1-5 04:01:35] [Broadlink RM] ** 
[2019-1-5 04:01:35] [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
[2019-1-5 04:01:35] [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/lprhodes or crypto https://goo.gl/bEn1RW.
[2019-1-5 04:01:35] [Broadlink RM] ** 
[2019-1-5 04:01:35] [Broadlink RM] ** Keep up to date with this plugin along with everything HomeKit and homebridge
[2019-1-5 04:01:35] [Broadlink RM] ** by signing up to my newsletter at http://workswith.io
[2019-1-5 04:01:35] [Broadlink RM] **
[2019-1-5 04:01:35] [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
[2019-1-5 04:01:35] [Broadlink RM] **
[2019-1-5 04:01:35] [Broadlink RM] **************************************************************************************************************
[2019-1-5 04:01:35] [Broadlink RM] 
[2019-1-5 04:01:35] [Broadlink RM] [INFO] Discovered Broadlink RM2 Pro Plus v2 (2787) at 192.168.0.5 (34:ea:34:cc:cd:d2)
  alexaHAP HAP Device discovered HomeBridgePi-E1A5 [ '192.168.0.24',
  '::73b3:223c:8a81:a629',
  'fe80::30dd:80:b769:1869',
  '192.168.0.26',
  '::22f8:ee7f:bc61:d6e8',
  'fe80::68ac:be87:52da:4915' ] +601ms
  alexaHAP HAP instance address: HomeBridgePi-E1A5 -> CC_22_3D_E3_CE_31.local -> 192.168.0.24 +1ms
  alexaHAP Homebridge instance discovered HomeBridgePi-E1A5 with 18 accessories +91ms
  alexaLocal reconnect +4s
  alexaLocal error { Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
 code: 5 } +171ms
[2019-1-5 04:01:44] [TplinkSmarthome] New Device Online: [Livingroom Light] bulb [8012A106DD9A4AD8042576E37A182E2318D0E1EB] 192.168.0.9 9999
[2019-1-5 04:01:44] [TplinkSmarthome] Adding: [Livingroom Light] bulb [8012A106DD9A4AD8042576E37A182E2318D0E1EB]
  alexaLocal reconnect +5s
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +100ms
  alexaLocal reconnect +5s
  alexaLocal error { Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:350:12)
    at work (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/lib/node_modules/homebridge-alexa/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
 code: 5 } +219ms
  alexaLocal reconnect +5s
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

**Comment by NorthernMan54** [comment]
@roberkane212 Sorry, missed this issue

alexaLocal error { Error: Connection refused: Not authorized

This means bad login/password.  Please check that the credentials your created on www.homebridge.ca are the same as the ones you put in your config.json.  If not, just create a new account.

**Comment by NorthernMan54** [comment]
Closed due to lack of activity
