### ISSUE TITLE
Cannot start SSDP Server despite adding "ssdp" : 1900, to the config

### ISSUE THREAD

**Issue by chongkwongsheng** [NorthernMan54/homebridge-alexa#18]
I have added the text of `"ssdp" : 1900,` to my config as instructed in the readme.md, however, when debugging, I notice that the SSDP is not started. How do I achieve this?

**Comment by chongkwongsheng** [comment]
**The start of my log also shows:**
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

**And the full text after my HomeKit code is as follows:**
 ssdp Not starting SSDP Server +0ms
  EventedHTTPServer Server listening on port 35635 +5ms
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:555:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:199:10)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)
    at EventedHTTPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:65:10)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1279:10)
    at nextTickCallbackWith1Arg (node.js:500:9)
    at process._tickCallback (node.js:422:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:140:18)
    at node.js:1043:3

**Comment by NorthernMan54** [comment]
The error is not caused by my changes but environment.  And when I say error I'm referring to this

Error: dns service error: name conflict
at Error (native)
at new Advertisement 

If you google this, you will find numerous solutions to this from homebridge issues.

**Comment by chongkwongsheng** [comment]
I found the error. It seems that there is no config.json in .homebridge. I missed this as I am using an app to run Homebridge and somehow it is working without this config file. I will have to drill down as to where the file resides. Sorry for the distraction.
