### ISSUE TITLE
homebridge-SamsungTizen update TypeError

### ISSUE THREAD

**Issue by Zaphor88** [NorthernMan54/homebridge-alexa#223]
Since I received the latest update from homebridge-samsungtizen I get the message:

TypeError: Cannot read property 'Manufacturer' of undefined
    at new Service (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Service.js:40:89)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:34:23)
    at Array.forEach (<anonymous>:null:null)
    at new Accessory (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:26:20)
    at Homebridge.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:24:21)
    at Array.forEach (<anonymous>:null:null)
    at new Homebridge (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:23:35)
    at Homebridges.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:17:22)
    at Array.forEach (<anonymous>:null:null)
    at new Homebridges (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:16:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:99:19)
    at HAPNodeJSClient.HAPaccessories (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:161:3)
    at Object.alexaDiscovery (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:93:14)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:33:20)
    at HAPNodeJSClient.emit (events.js:159:13)
    at HAPNodeJSClient._discoveryEnd (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:147:8)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

What can I do?

curl -X it does not work: Failed to connect .... Connection refused

**Comment by tavicu** [comment]
Hei! I have seen the problem and tried to diagnose it.

Looks like homebridge-alexa don't know about [publishExternalAccessories](https://github.com/nfarina/homebridge/blob/358794e8405174291f4c36fff7671e45199533fc/lib/api.js#L104)

**Comment by NorthernMan54** [comment]
@Zaphor88 Try removing homebridge-alexa from your config.json, then restart homebridge, then run curl

homebridge-alexa is causing homebridge to exit so CURL isn't working

**Comment by tavicu** [comment]
I managed to find a solution. Somehow homebridge-alexa expects the information service to be first.

I will push an update in a few minutes.

**Comment by NorthernMan54** [comment]
@tavicu Correct, I'm parsing the HAP accessories object to find accessories, and assumed that the first service is the information service

**Comment by tavicu** [comment]
Pushed a new version. Waiting for feedback :) 

@NorthernMan54 @Zaphor88 @adamstamper

**Comment by Zaphor88** [comment]
grandest homebridge does not crash any more.  

but now I can not add the TV in the home app.  it does not exist in „Add Devices“.

**Comment by adamstamper** [comment]
Great work @tavicu (and @NorthernMan54) - all fixed and working well together again! Thanks for speedy action to resolve.

**Comment by NorthernMan54** [comment]
@Zaphor88 Sounds like you your TV is already "added" hence not showing up.  If things are out of whack, you would need to delete the .homebridge/accessories and .homebridge/persist directories.  Down side is that everything needs to be configured again in the Home app.

**Comment by NorthernMan54** [comment]
As that is not a homebridge-alexa issue, I'm closing this.  Tks @tavicu for the assist on this issue
