### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by DerMatteo** [NorthernMan54/homebridge-alexa#241]
**I cant install the plugin. It says:** 
`npm WARN saveError ENOENT: no such file or directory, open '/var/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/var/package.json'
npm WARN var No description
npm WARN var No repository field.
npm WARN var No README data
npm WARN var No license field.

+ homebridge-alexa@0.4.25
updated 1 package and audited 1933 packages in 27.312s
found 0 vulnerabilities`

------------------------------------------

**"npm i homebridge-alexa@lastest" says this:**
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-alexa@lastest
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-26T17_26_35_351Z-debug.log`

------------------------------------------

**Homebridge says:**
`"Jul 26 19:28:11 SmartHomeV2 systemd[1]: Started Matteo Homebridge Server.
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]: [2019-7-26 7:28:18 PM] Loaded config.json with 5 accessories and 1 platforms.
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]: [2019-7-26 7:28:18 PM] ---
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]: [2019-7-26 7:28:18 PM] No plugins found. See the README for information on installing plugins.
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]: [2019-7-26 7:28:18 PM] Loading 1 platforms...
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]: [2019-7-26 7:28:18 PM] Error: The requested platform 'Alexa' was not registered by any plugin.
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jul 26 19:28:18 SmartHomeV2 homebridge[4905]: [2019-7-26 7:28:18 PM] Got SIGTERM, shutting down Homebridge...
Jul 26 19:28:23 SmartHomeV2 systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jul 26 19:28:23 SmartHomeV2 systemd[1]: homebridge.service: Failed with result 'exit-code'.
Jul 26 19:28:34 SmartHomeV2 systemd[1]: homebridge.service: Service RestartSec=10s expired, scheduling restart.
Jul 26 19:28:34 SmartHomeV2 systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 24.
"`

**Comment by DerMatteo** [comment]
Solved! Who ever has this problem: npm install -g homebridge-alexa !!! Then it works! I didnt read the instruction completely!
