### ISSUE TITLE
Error when starting homebridge

### ISSUE THREAD

**Issue by robbbyc** [NorthernMan54/homebridge-alexa#25]
Hi,

I installed homebridge on Windows 10 with the latest nodejs 6.11.2 and I get the following error when starting homebridge ?

[2017-8-19 23:04:05] Running : homebridge-homewizard 0.0.59
[2017-8-19 23:04:06] Successfully retrieved accessories from HomeWizard
[2017-8-19 23:04:06] Initializing platform accessory 'Home Preset'...
[2017-8-19 23:04:06] Failed to retrieve accessories from HomeWizard
[2017-8-19 23:04:06] TypeError: Cannot read property 'length' of undefined
    at Characteristic.validateValue (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Characteristic.js:225:19)
    at Characteristic.setValue (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Characteristic.js:273:19)
    at Service.setCharacteristic (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Service.js:178:32)
    at HomeWizardPreset._setupInformationService (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\dist\accessories\accessory.js:39:162)
    at HomeWizardPreset.getServices (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\dist\accessories\accessory.js:57:12)
    at Server._createAccessory (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:380:36)
    at Server.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:366:32)
    at C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:16:19
    at C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\dist\platform.js:72:9
    at _fulfilled (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\node_modules\q\q.js:816:13)
    at C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\node_modules\q\q.js:624:44
    at runSingle (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\node_modules\q\q.js:137:13)
    at flush (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-homewizard\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

Thx
Robby

**Comment by NorthernMan54** [comment]
Have you tried the latest regular version?  This looks like an error from the recent iOS 11 changes, and my version is one or two days behind. Give me a few days to catch up.

**Comment by NorthernMan54** [comment]
I updated to the latest version of homebridge this morning, please try again.

**Comment by robbbyc** [comment]
Thx for the update but now I get another error:

C:\Users\user>homebridge
module.js:471
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\ssdp.js:5:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I already tried uninstalling and reinstalling homebridge.

Thx
Robby

**Comment by robbbyc** [comment]
I manually installed lodash and async and now it works !

**Comment by NorthernMan54** [comment]
Tks for the update on how you got it working.  It looks like I dropped those packages as part of the merge.   I have gone and readded them back.
