### ISSUE TITLE
Alexa stopped working

### ISSUE THREAD

**Issue by SzilagyiR** [NorthernMan54/homebridge-alexa#256]
Hi! 

I use homebridge-alexa for years, without any peoblem, but today she stopped working. The Homebridge works fine, but Alexa said “XY Is not responding”.

Trying remove and discover devices, but nothing happen. Trying reboot PI, and Alexa, also nothing. 

Have you any idea, what is wrong? I’m using homebridge-alexa version 1.

Thanks!

**Comment by SzilagyiR** [comment]
I’m using homebridge-alexa version 1.

**Comment by SzilagyiR** [comment]
I am trying to use version 2, I follow the setup guide, but Alexa not discover anything.
Here's my log:
root@raspberrypi:~# DEBUG=alexa* homebridge -I
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/15/2019, 8:30:39 AM] Loaded plugin: homebridge-alexa
[9/15/2019, 8:30:39 AM] Registering platform 'homebridge-alexa.Alexa'
[9/15/2019, 8:30:39 AM] ---
[9/15/2019, 8:30:40 AM] Loaded plugin: homebridge-broadlink-rm
[9/15/2019, 8:30:40 AM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[9/15/2019, 8:30:40 AM] ---
[9/15/2019, 8:30:40 AM] Loaded plugin: homebridge-delay-switch
[9/15/2019, 8:30:40 AM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[9/15/2019, 8:30:40 AM] ---
[9/15/2019, 8:30:41 AM] Loaded plugin: homebridge-mqtt-switch-tasmota
[9/15/2019, 8:30:41 AM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[9/15/2019, 8:30:41 AM] ---
[9/15/2019, 8:30:41 AM] Loaded plugin: homebridge-winpc
[9/15/2019, 8:30:41 AM] Registering accessory 'homebridge-winpc.WinPC'
[9/15/2019, 8:30:41 AM] ---
[9/15/2019, 8:30:41 AM] Loaded config.json with 19 accessories and 1 platforms.
[9/15/2019, 8:30:41 AM] ---
[9/15/2019, 8:30:41 AM] Loading 1 platforms...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing BroadlinkRM platform...
[9/15/2019, 8:30:41 AM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[9/15/2019, 8:30:41 AM] [Broadlink RM] TV Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Receiver Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Media Player Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Shutdown Movie Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Shutdown Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Watch a Movie Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Use Pc Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Watch Tv Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Play Music Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Play Movie Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Pause Movie Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Stop Movie Accessory Ready
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Learn'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'TV'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Receiver'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Media Player'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Shutdown Movie'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Shutdown'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Watch a Movie'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Use Pc'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Watch Tv'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Play Music'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Play Movie'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Pause Movie'...
[9/15/2019, 8:30:41 AM] [Broadlink RM] Initializing platform accessory 'Stop Movie'...
[9/15/2019, 8:30:41 AM] Loading 19 accessories...
[9/15/2019, 8:30:41 AM] [WorkshopDelayOn] Initializing DelaySwitch accessory...
[9/15/2019, 8:30:41 AM] [WorkshopDelayOff] Initializing DelaySwitch accessory...
[9/15/2019, 8:30:41 AM] [GarageDelayOn] Initializing DelaySwitch accessory...
[9/15/2019, 8:30:41 AM] [GarageDelayOff] Initializing DelaySwitch accessory...
[9/15/2019, 8:30:41 AM] [Pc] Initializing WinPC accessory...
[9/15/2019, 8:30:41 AM] [Pc] Setting info: {"serialnumber":"Unknown","model":"Windows PC","manufacterer":"Microsoft","name":"Windows PC","softwareversion":"Unknown","manufacturer":"Microsoft"}
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[9/15/2019, 8:30:41 AM] [Micro Pc] Initializing WinPC accessory...
[9/15/2019, 8:30:41 AM] [Micro Pc] Setting info: {"serialnumber":"Unknown","model":"Windows PC","manufacterer":"Microsoft","name":"Windows PC","softwareversion":"Unknown","manufacturer":"Microsoft"}
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[9/15/2019, 8:30:41 AM] [gate] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:41 AM] [gate] Nazwa do RESULT  power
[9/15/2019, 8:30:41 AM] [door] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [door] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [stand lamp] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [stand lamp] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [living room light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [living room light] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [upstairs light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [upstairs light] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [office room light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [office room light] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [child room light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [child room light] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [kitchen light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [kitchen light] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [dining room light 1] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [dining room light 1] Nazwa do RESULT  POWER1
[9/15/2019, 8:30:42 AM] [dining room light 2] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [dining room light 2] Nazwa do RESULT  POWER2
[9/15/2019, 8:30:42 AM] [heater] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [heater] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [Workshop light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [Workshop light] Nazwa do RESULT  power
[9/15/2019, 8:30:42 AM] [Garage light] Initializing mqtt-switch-tasmota accessory...
[9/15/2019, 8:30:42 AM] [Garage light] Nazwa do RESULT  power
Setup Payload:
X-HM://0023ISYWY5IFC
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:  
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[9/15/2019, 8:30:42 AM] Homebridge is running on port 51826.
[9/15/2019, 8:30:42 AM] [Pc] start polling..
[9/15/2019, 8:30:42 AM] [Pc] getPowerState - actual mode
[9/15/2019, 8:30:42 AM] [Micro Pc] start polling..
[9/15/2019, 8:30:42 AM] [Micro Pc] getPowerState - actual mode
[9/15/2019, 8:30:42 AM] [Broadlink RM] TV getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Receiver getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Media Player getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Shutdown Movie getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Shutdown getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Watch a Movie getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Use Pc getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Watch Tv getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Play Music getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Play Movie getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Pause Movie getSwitchState: false
[9/15/2019, 8:30:42 AM] [Broadlink RM] Stop Movie getSwitchState: false
[9/15/2019, 8:30:42 AM] [Micro Pc] getPowerState - actual mode - current state: true
[9/15/2019, 8:30:42 AM] [Micro Pc] event - status poller - new state:  true
[9/15/2019, 8:30:42 AM] [Micro Pc] setPowerState - polling mode, ignore, state: true
[9/15/2019, 8:30:42 AM] [Broadlink RM] [INFO] Discovered Broadlink RM Mini (2737) at 192.168.0.39 (34:ea:34:b2:f3:97)
[9/15/2019, 8:30:43 AM] [Broadlink RM] 
[9/15/2019, 8:30:43 AM] [Broadlink RM] **************************************************************************************************************
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** Welcome to version 3.5.5 of the Homebridge Broadlink RM Plugin!
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** 
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** Find out what's in the latest release here: https://github.com/lprhodes/homebridge-broadlink-rm/releases
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** 
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/lprhodes or crypto https://goo.gl/bEn1RW.
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** 
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** Keep up to date with this plugin along with everything HomeKit and homebridge
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** by signing up to my newsletter at http://workswith.io
[9/15/2019, 8:30:43 AM] [Broadlink RM] **
[9/15/2019, 8:30:43 AM] [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
[9/15/2019, 8:30:43 AM] [Broadlink RM] **
[9/15/2019, 8:30:43 AM] [Broadlink RM] **************************************************************************************************************
[9/15/2019, 8:30:43 AM] [Broadlink RM] 
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Shutdown Movie: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Shutdown: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Watch a Movie: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Use Pc: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Watch Tv: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Play Music: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Play Movie: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Pause Movie: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:43 AM] [Broadlink RM] [Warning] Stop Movie: The "switch-multi" accessory is now deprecated and shall be removed in the future. Check out the updated "switch" documentation at http://github.com/lprhodes/homebridge-broadlink-rm
[9/15/2019, 8:30:45 AM] [Pc] getPowerState - actual mode - current state: false
[9/15/2019, 8:30:45 AM] [Pc] event - status poller - new state:  false
[9/15/2019, 8:30:45 AM] [Pc] setPowerState - polling mode, ignore, state: false
[9/15/2019, 8:30:48 AM] [Broadlink RM] TV getSwitchState: false
[9/15/2019, 8:30:48 AM] [Broadlink RM] Receiver getSwitchState: false
[9/15/2019, 8:30:48 AM] [Broadlink RM] Media Player getSwitchState: false
[9/15/2019, 8:30:48 AM] [Broadlink RM] Shutdown Movie getSwitchState: false
[9/15/2019, 8:30:49 AM] [Broadlink RM] Shutdown getSwitchState: false
[9/15/2019, 8:30:49 AM] [Broadlink RM] Watch a Movie getSwitchState: false
[9/15/2019, 8:30:49 AM] [Broadlink RM] Use Pc getSwitchState: false
[9/15/2019, 8:30:49 AM] [Broadlink RM] Watch Tv getSwitchState: false

**Comment by NorthernMan54** [comment]
Looking at the log file, I don’t see any logging from the Alexa plugin.  Is it properly configured in the config.json?

**Comment by SzilagyiR** [comment]
I see the same problem, checking the config.json but everything seems fine to me, no error message.

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"

    },
    
    "platforms": [{
         "platform": "Alexa",
         "name": "Alexa",
         "username": "xxxxx",
         "password": "xxxxx",
         "routines": true,
	 "debug": true
    }
    ],
    


    "accessories": [

        {

**Comment by SzilagyiR** [comment]
I think i found the probelm in the confi.json, but new error message come:

 hapNodeJSClient Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +0ms
[9/16/2019, 10:41:43 AM] Homebridge is running on port 51826.
  alexaLocal connect command/Sziszialexa/# +683ms
  hapNodeJSClient HAP Device discovered Aqara Hub-5543 [ '192.168.0.38', 'fe80::7e49:ebff:fe92:c1a9' ] +724ms
  hapNodeJSClient HAP instance address: Aqara Hub-5543 -> Aqara-Hub-5543.local -> 192.168.0.38:4567 +14ms
  hapNodeJSClient HAP Device discovered MJCTD02YL [ '192.168.0.37', 'fe80::4231:3cff:fe3e:b7b4' ] +53ms
  hapNodeJSClient HAP instance address: MJCTD02YL -> MiBedsideLamp2-B7B4.local -> 192.168.0.37:80 +1ms
  hapNodeJSClient HAP Discover failed Aqara Hub-5543 http://192.168.0.38:4567 error code 470 +91ms
  hapNodeJSClient HAP Discover failed MJCTD02YL http://192.168.0.37:80 error code 470 +36ms
  hapNodeJSClient HAP Device discovered Homebridge [ 'fe80::1f61:5438:f646:2454', '192.168.0.40' ] +348ms
  hapNodeJSClient HAP instance address: Homebridge -> raspberrypi.local -> 192.168.0.40:51826 +1ms
  hapNodeJSClient Homebridge instance discovered Homebridge with 1 accessories +56ms
  hapNodeJSClient Ending Homebridge instance discovery +19s
  alexaActions alexaDiscovery +0ms
[9/16/2019, 10:42:03 AM] [Alexa] ERROR: HAP Discovery failed, please review config
  alexaActions registerEvents [] +41ms
  alexaLocal Emitting Alexa.Discovery +50s
  alexaActions alexaDiscovery +30s
[9/16/2019, 10:42:33 AM] [Alexa] ERROR: HAP Discovery failed, please review config

**Comment by NorthernMan54** [comment]
Look at that log carefully, it is saying that it found one instance of homebridge with one accessory.  Is that correct?

**Comment by SzilagyiR** [comment]
Yes, it is correct. But I Alexa not find that when I discovering.
I have some Sonoff swithes, they are missing from homekit app, and Alexa.

**Comment by NorthernMan54** [comment]
I’m lost here, your saying that you have 1 homebridge instance and that the discovery was correct.  And the log shows that homebridge has 1 accessory

**Comment by SzilagyiR** [comment]
I'm lost too :)
I have 20+ device, not 1.
I'm using homebrdige-alexa plugin V1 to allow Alexa to find deveral homebridge devices, the V2 plugin not the same?

**Comment by NorthernMan54** [comment]
Did discovery find all your homebridge instanced?

**Comment by SzilagyiR** [comment]
Yes, only one instance, but my devices missing.

Here is my full config.json:
[config.txt](https://github.com/NorthernMan54/homebridge-alexa/files/3616410/config.txt)

**Comment by NorthernMan54** [comment]
Something odd is going on

If you wait 15 minutes, it will run device discovery again and may return all devices.

If it doesn’t work, please supply a homebridge accessory dump, details are in the README

**Comment by SzilagyiR** [comment]
Nothing happen, still missing my devices, but seems the homebridge stuck in this point and not start the other plugins.

**Comment by SzilagyiR** [comment]
I tried to modify the config.json, I thing the problem is there, here the result:

root@raspberrypi:/home/pi# homebridge -I
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[9/17/2019, 11:28:50 AM] Loaded plugin: homebridge-alexa
[9/17/2019, 11:28:50 AM] Registering platform 'homebridge-alexa.Alexa'
[9/17/2019, 11:28:50 AM] ---
[9/17/2019, 11:28:52 AM] Loaded plugin: homebridge-broadlink-rm
[9/17/2019, 11:28:52 AM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[9/17/2019, 11:28:52 AM] ---
[9/17/2019, 11:28:52 AM] Loaded plugin: homebridge-delay-switch
[9/17/2019, 11:28:52 AM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[9/17/2019, 11:28:52 AM] ---
[9/17/2019, 11:28:52 AM] Loaded plugin: homebridge-mqtt-switch-tasmota
[9/17/2019, 11:28:52 AM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[9/17/2019, 11:28:52 AM] ---
[9/17/2019, 11:28:52 AM] Loaded plugin: homebridge-winpc
[9/17/2019, 11:28:52 AM] Registering accessory 'homebridge-winpc.WinPC'
[9/17/2019, 11:28:52 AM] ---
[9/17/2019, 11:28:52 AM] Loaded config.json with 31 accessories and 2 platforms.
[9/17/2019, 11:28:52 AM] ---
[9/17/2019, 11:28:52 AM] Loading 2 platforms...
[9/17/2019, 11:28:52 AM] [Alexa] Initializing Alexa platform...
[9/17/2019, 11:28:53 AM] [Alexa] homebridge-alexa v0.4.39, node v7.8.0, homebridge v0.4.38
[9/17/2019, 11:28:53 AM] [Broadlink RM] Initializing BroadlinkRM platform...
[9/17/2019, 11:28:53 AM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[9/17/2019, 11:28:53 AM] [Broadlink RM] No accessories have been added to the "Broadlink RM" platform config.
[9/17/2019, 11:28:53 AM] [Broadlink RM] Initializing platform accessory 'Learn'...
[9/17/2019, 11:28:53 AM] [Broadlink RM] Initializing platform accessory 'Scan Frequency'...
[9/17/2019, 11:28:53 AM] Loading 31 accessories...
[9/17/2019, 11:28:53 AM] [WorkshopDelayOn] Initializing DelaySwitch accessory...
[9/17/2019, 11:28:53 AM] [WorkshopDelayOff] Initializing DelaySwitch accessory...
[9/17/2019, 11:28:53 AM] [GarageDelayOn] Initializing DelaySwitch accessory...
[9/17/2019, 11:28:53 AM] [GarageDelayOff] Initializing DelaySwitch accessory...
[9/17/2019, 11:28:53 AM] [Pc] Initializing WinPC accessory...
[9/17/2019, 11:28:53 AM] [Pc] Setting info: {"serialnumber":"Unknown","model":"Windows PC","manufacterer":"Microsoft","name":"Windows PC","softwareversion":"Unknown","manufacturer":"Microsoft"}
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[9/17/2019, 11:28:53 AM] [Micro Pc] Initializing WinPC accessory...
[9/17/2019, 11:28:53 AM] [Micro Pc] Setting info: {"serialnumber":"Unknown","model":"Windows PC","manufacterer":"Microsoft","name":"Windows PC","softwareversion":"Unknown","manufacturer":"Microsoft"}
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[9/17/2019, 11:28:53 AM] [gate] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [gate] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [door] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [door] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [stand lamp] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [stand lamp] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [living room light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [living room light] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [upstairs light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [upstairs light] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [office room light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [office room light] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [child room light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [child room light] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [kitchen light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [kitchen light] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [dining room light 1] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [dining room light 1] Nazwa do RESULT  POWER1
[9/17/2019, 11:28:53 AM] [dining room light 2] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [dining room light 2] Nazwa do RESULT  POWER2
[9/17/2019, 11:28:53 AM] [heater] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [heater] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [Workshop light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [Workshop light] Nazwa do RESULT  power
[9/17/2019, 11:28:53 AM] [Garage light] Initializing mqtt-switch-tasmota accessory...
[9/17/2019, 11:28:53 AM] [Garage light] Nazwa do RESULT  power
/usr/local/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:267:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by NorthernMan54** [comment]
I’m not sure what is causing this error, but it isn’t my plugin directly. I’m wondering if your missing something from the config.json

**Comment by SzilagyiR** [comment]
Hi!

I found the problem in the config.json, the BroadlinkRM plugin stuck together with yours.
Here is the sample, if anybody stuck in this robelm, like me :)
[config.json sample.txt](https://github.com/NorthernMan54/homebridge-alexa/files/3620915/config.json.sample.txt)


Thank you, for your help!
