### ISSUE TITLE
Can't get homebridge-alexa to work

### ISSUE THREAD

**Issue by nedisonn** [NorthernMan54/homebridge-alexa#259]
When I launch homebridge, it works for awhile and then when I try to use alexa to recognize my devices, it throws this error:

`TypeError: Cannot read property 'getCharacteristic' of undefined
    at Service.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Service.js:188:60)
    at Accessory.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:142:27)
    at Homebridge.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:161:27)
    at Homebridges.toAlexa (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:47:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:100:28)
    at HAPNodeJSClient.HAPaccessories (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:163:3)
    at Object.alexaDiscovery (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:93:14)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:33:20)
    at HAPNodeJSClient.emit (events.js:198:13)
    at HAPNodeJSClient._discoveryEnd (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:149:8)
`
And it closes off homebridge.
I tried installing version 1 too, no luck. I tried reinstalling it, no luck.
Is this a known bug?

**Comment by nedisonn** [comment]
Found out it was a pugin problem.... can't get HTTP-RGB to work
