### ISSUE TITLE
Installing additional plugin error

### ISSUE THREAD

**Issue by jat80** [NorthernMan54/homebridge-alexa#27]
Hi again,

I tried to install another homebridge plugin but it didn't work (well I couldn't get it to work) so I uninstalled the plugin and removed the code from the config but now my homebridge plugins won't work.

I get this error when just trying run homebridge:

$ homebridge
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by NorthernMan54** [comment]
To fix this you need to re-install my version of homebridge again.

**Comment by jat80** [comment]
That's what I thought and I did but did not work still get this:

$ sudo homebridge
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by jat80** [comment]
how do I delete everything related to homebridge and start again?

**Comment by NorthernMan54** [comment]
sudo rm -rf /usr/local/lib/node_modules

Then you can reinstall from scratch

**Comment by jat80** [comment]
Tried that @NorthernMan54 but that didn't work either.  Back to the same error messages??  I've got Xcode installed on my mac, i've just installed the latest nodejs from the website as per instructions https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-macOS but still getting this after:

homebridge
module.js:491
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

i'm stumped.

**Comment by NorthernMan54** [comment]
2 different things to try

1) Try this command first, then reinstall homebridge

sudo su -

2) or the fix from this issue

https://github.com/nfarina/homebridge/issues/1419

**Comment by jat80** [comment]
ok the link to the above issue has helped.  Now I can run it but get this error.  This is just on the normal homebridge, I haven't installed your version over the top yet.  The camera one is irrelevant as I'm not using it at the moment.  Thanks for your help, really appreciate it.

$ homebridge
[2017-9-7 14:46:28] Loaded plugin: homebridge-broadlink-rm
[2017-9-7 14:46:28] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2017-9-7 14:46:28] ---
[2017-9-7 14:46:28] Loaded config.json with 0 accessories and 2 platforms.
[2017-9-7 14:46:28] ---
[2017-9-7 14:46:28] Loading 2 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Camera-ffmpeg' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

**Comment by NorthernMan54** [comment]
Check your config.json, you have the camera plugin listed but not installed.

**Comment by jat80** [comment]
Thanks @NorthernMan54 Working fine now!
