### ISSUE TITLE
Homebridge Crash after Homebridge-alexa Setup

### ISSUE THREAD

**Issue by denzel1994** [NorthernMan54/homebridge-alexa#271]
Hello together,

after installation and adding the needed information to the config.json I restart my Homebridge and get the following error.
The Homebridge then shuts down.

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:445:26)
    at Request._callback (/usr/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1083:12)`

**Comment by NorthernMan54** [comment]
Are you running in DEBUG mode, and can you share a bit more log from before the error
