### ISSUE TITLE
PowerController Using Old IP address

### ISSUE THREAD

**Issue by chrisp79** [NorthernMan54/homebridge-alexa#282]
Hi. I installed a set of 3 LinkSys Velop nodes today and disabled the WIFI on my router. My Raspberry Pi is connected to one of the nodes via ethernet (it was previously connected directly to my router). Homekit is working fine but the Alexa skill is not. What I see in Homebridge is as follows,,,

[12/21/2019, 5:59:41 PM] [Alexa] alexaDiscovery - returned 40 devices
[12/21/2019, 5:59:54 PM] [Fan] Turning Fan on
[12/21/2019, 6:01:15 PM] [Alexa] PowerController TurnOn 192.168.0.58 51827 undefined { Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:849:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', connect: true, attempts: 1 }

It looks like PowerController is still trying to talk to the Raspberry Pi's old PI address (it's now 192.168.1.xxx) and I'm not sure / can't remember where it's getting this IP address from so I can't change it and see if that fixes the problem.

Any ideas would be much appreciated!
Thanks, Chris

**Comment by NorthernMan54** [comment]
Ask Alexa to discover devices and she will update the device information with new ip

**Comment by chrisp79** [comment]
Thanks! She sorted herself out a couple of hours later actually without me needing to do that. As ever, really appreciate your help!
