### ISSUE TITLE
Can't start Homebridge

### ISSUE THREAD

**Issue by sdorilas** [NorthernMan54/homebridge-alexa#288]
====================
[1/12/2020, 8:18:21 PM] ERROR LOADING PLUGIN homebridge-alexa:
[1/12/2020, 8:18:21 PM] Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/store.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by NorthernMan54** [comment]
Please try installing the plugin again, never seen this before.

Are you running on something beside a raspberryPI?

**Comment by sdorilas** [comment]
No, i'm running on a rasperry pie running HOOBS. Everything had been working fine for months, I went to update a plugin today and it broke while updating the plugin. Now i'm getting that error, I have tried installing the plugin multiple times. Should I uninstall before installing again?

**Comment by NorthernMan54** [comment]
I can’t hurt to remove the plugin and re-install

**Comment by sdorilas** [comment]
Tried it..changed nothing. Exactly the same as before.

**Comment by NorthernMan54** [comment]
Command line or GUI?

Sounds like the install is having errors of some type, but they aren't being displayed in the GUI installer

Just tested from my machine, and everything is fine

```
sheldon:~$ sudo npm install -g homebridge-alexa
+ homebridge-alexa@0.4.51
added 171 packages from 135 contributors in 27.663s
```

**Comment by sdorilas** [comment]
I don’t believe the installer is having any issues either. It installs successfully but I appear to be having another issue. Thank you for your help!
