### ISSUE TITLE
Homebridge stop working

### ISSUE THREAD

**Issue by SzilagyiR** [NorthernMan54/homebridge-alexa#29]
Hi!

I use your Homebridge for several months, without error, but the past 3 days it crash one time per day.

Here is the log:
[10/8/2017, 9:44:48 AM] [Pc] getPowerState - actual mode - current state: false
[10/8/2017, 9:45:45 AM] [Pc] start polling..
[10/8/2017, 9:45:45 AM] [Pc] getPowerState - actual mode
[10/8/2017, 9:45:45 AM] [Micro Pc] start polling..
[10/8/2017, 9:45:45 AM] [Micro Pc] getPowerState - actual mode
[10/8/2017, 9:45:45 AM] [Micro Pc] getPowerState - actual mode - current state: true
[10/8/2017, 9:45:48 AM] [Pc] getPowerState - actual mode - current state: false
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389
  var mac = hueDevices[lightid].uniqueid.split(':');
                               ^

TypeError: Cannot read property 'uniqueid' of undefined
    at _getAid (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389:32)
    at hueToHKCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:179:15)
    at Object.handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:88:24)
    at HAPServer._handleHueApi (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:923:7)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:220:47)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Thanks!

**Comment by NorthernMan54** [comment]
On your Alexa app, go to setting smart home devices and forget all.  Then rediscover devices again.

**Comment by SzilagyiR** [comment]
Thanks the hint, I'm testing it!

**Comment by SzilagyiR** [comment]
Seems to be fine, thanks for your help!
