### ISSUE TITLE
Alexa Not Controller Lights After Update

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [NorthernMan54/homebridge-alexa#296]
Hi,
 Been using this plugin for quite a while, I just updated it, and did a refresh of all my devices, now I cant get Alexa to control any off my lights, the Alexa app will show the light state as I toggle it in Homekit, but if I try and control with Alexa, the switches wont respond.

Below is what my log starts pumping out after I try to control a light:

[2/15/2020, 8:32:59 AM] [Alexa] PowerController TurnOff 192.168.0.183 32223 undefined Error: Homebridge auth failed, invalid PIN undefined
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:200:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2/15/2020, 8:33:02 AM] [Alexa] PowerController TurnOff 192.168.0.183 32223 undefined Error: Homebridge auth failed, invalid PIN undefined
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:200:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2/15/2020, 8:33:06 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:09 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:12 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:15 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:18 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:21 AM] [Control-Panel] [admin] Accessory layout changes saved.
[2/15/2020, 8:33:21 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:24 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:27 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:30 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:33 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:36 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:39 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:42 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:45 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:48 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:51 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:54 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:33:57 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:00 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:03 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:06 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:09 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:12 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:15 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:18 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:21 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:24 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:27 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:30 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:33 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:36 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:38 AM] [Alexa] alexaDiscovery - returned 37 devices
[2/15/2020, 8:34:39 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:42 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:45 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:48 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:51 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:54 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:34:57 AM] [Broadlink RM] Kitchen getSwitchState: true
[2/15/2020, 8:35:00 AM] [Broadlink RM] Kitchen get

Not sure if something else in my system needs updating.

**Comment by NorthernMan54** [comment]
This is the issue

2/15/2020, 8:32:59 AM] [Alexa] PowerController TurnOff 192.168.0.183 32223 undefined Error: Homebridge auth failed, invalid PIN

Have you changed the homebridge pin or something?

**Comment by Kung-Foo-Kamel** [comment]
No, same install and same setup for a few years now, just been updating it, I seen this too but couldnt work out why.

Can I re-authorise the plugin?

**Comment by Kung-Foo-Kamel** [comment]
Okay, I worked it out, had to add the "pin" command, as I changed the pin in Homebridge when I first set it up about 2 years ago, this Plugin was working fine with my pin, but I'm assuming the newer version is trying to use the "default" pin.

So all good now, were back in business, cheers.
