### ISSUE TITLE
No Devices Added to Alexa via HomeBridge-Alexa Plugin

### ISSUE THREAD

**Issue by davewehr** [NorthernMan54/homebridge-alexa#304]
I have the homebridge.ca plugin linked. Logging onto the site shows the date of the last plugin login as of today:

![image](https://user-images.githubusercontent.com/62607402/77438701-86bc7b80-6dbc-11ea-9946-65f33982195c.png)

I am running my HomeBridge in insecure mode (-I)

I even get the little Alexa contact sensor that says whether the service is disconnected, this showed up in HomeKit once I got it all installed and configured.

I have some dummy switches in HomeBridge (occupancy-delay, for example) but when I ask Alexa to discover devices nothing is added.

Below is some of my logs and config. It complains a lot about duplicate devices, but 

{
            "name": "Alexa",
            "username": "obscuredusername",
            "password": "obscuredpassword",
            "pin": "obscuredpin",
            "routines": true,
            "platform": "Alexa"
        }

[3/24/2020, 4:27:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 4:42:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 4:42:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 4:42:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 4:42:08 AM] [Alexa] WARNING: Duplicate device name Visibility: 15 km
[3/24/2020, 4:42:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 4:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 4:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 4:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 4:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Visibility: 15 km
[3/24/2020, 4:42:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 4:57:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 4:57:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 4:57:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 4:57:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 4:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 4:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 4:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 4:57:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 5:12:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 5:12:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 5:12:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 5:12:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 5:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 5:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 5:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 5:12:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 5:26:01 AM] [Occupancy] checkOccupancy: 1
[3/24/2020, 5:26:17 AM] [Occupancy] Timer started: 35
[3/24/2020, 5:26:17 AM] [Occupancy] checkOccupancy: 0
[3/24/2020, 5:26:52 AM] [Occupancy] Timer stopped
[3/24/2020, 5:27:08 AM] [Occupancy] checkOccupancy: 1
[3/24/2020, 5:27:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 5:27:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 5:27:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 5:27:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 5:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 5:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 5:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 5:27:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 5:27:34 AM] [Occupancy] Timer started: 35
[3/24/2020, 5:27:34 AM] [Occupancy] checkOccupancy: 0
[3/24/2020, 5:28:09 AM] [Occupancy] Timer stopped
[3/24/2020, 5:28:45 AM] [Occupancy] checkOccupancy: 1
[3/24/2020, 5:28:58 AM] [Occupancy] Timer started: 35
[3/24/2020, 5:28:58 AM] [Occupancy] checkOccupancy: 0
[3/24/2020, 5:29:33 AM] [Occupancy] Timer stopped
[3/24/2020, 5:42:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 5:42:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 5:42:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 5:42:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 5:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 5:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 5:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 5:42:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 5:57:08 AM] [Alexa] WARNING: Duplicate device name Air Pressure: 1020 hPa
[3/24/2020, 5:57:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 5:57:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 5:57:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 5:57:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 5:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Air Pressure: 1020 hPa
[3/24/2020, 5:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 5:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 5:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 5:57:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 6:12:08 AM] [Alexa] WARNING: Duplicate device name Air Pressure: 1020 hPa
[3/24/2020, 6:12:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 6:12:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 6:12:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 6:12:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 6:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Air Pressure: 1020 hPa
[3/24/2020, 6:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 6:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 6:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 6:12:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 6:27:08 AM] [Alexa] WARNING: Duplicate device name Air Pressure: 1020 hPa
[3/24/2020, 6:27:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 6:27:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 6:27:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 6:27:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 6:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Air Pressure: 1020 hPa
[3/24/2020, 6:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 6:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 6:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 6:27:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 6:42:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 6:42:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 6:42:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 6:42:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 6:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 6:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 6:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 6:42:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 6:57:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 6:57:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 6:57:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 6:57:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 6:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 6:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 6:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 6:57:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 7:12:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 7:12:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 7:12:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 7:12:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 7:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 7:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 7:12:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 7:12:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 7:27:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 7:27:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 7:27:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 7:27:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 7:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 7:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 7:27:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 7:27:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 7:42:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 7:42:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 7:42:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 7:42:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 7:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 7:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 7:42:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 7:42:08 AM] [Alexa] alexaDiscovery - returned 32 devices
[3/24/2020, 7:57:08 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/24/2020, 7:57:08 AM] [Alexa] WARNING: Duplicate device name Rain
[3/24/2020, 7:57:08 AM] [Alexa] WARNING: Duplicate device name Snow
[3/24/2020, 7:57:08 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/24/2020, 7:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Dew Point
[3/24/2020, 7:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Rain
[3/24/2020, 7:57:08 AM] [Alexa] ERROR: Parsing failed, duplicate endpointID. Snow
[3/24/2020, 7:57:08 AM] [Alexa] alexaDiscovery - returned 32 devices

[3/24/2020, 10:44:56 AM] [Alexa] Initializing Alexa platform...
[3/24/2020, 10:44:56 AM] [Alexa] homebridge-alexa v0.4.56, node v12.16.1, homebridge v0.4.53
[3/24/2020, 10:44:56 AM] [Alexa] Initializing platform accessory 'Alexa'...
[3/24/2020, 10:44:56 AM] Loading 2 accessories...

**Comment by NorthernMan54** [comment]
These error messages are causing no devices to appear in Alexa

Can you adjust the names so they are not duplicate?

**Comment by davewehr** [comment]
Well I just tried to rename one of the duplicates to see if it disappears from the logs, but it still shows up as "Dew Point" in the log:

![image](https://user-images.githubusercontent.com/62607402/77467652-c72ef000-6de2-11ea-8550-87987e527ea7.png)

**Comment by NorthernMan54** [comment]
Where did you rename it?  in config.json or ???

**Comment by davewehr** [comment]
Here is the config.json associated with the "dew point" sensors:

![image](https://user-images.githubusercontent.com/62607402/77562495-77116580-6e96-11ea-8867-5c979cb9d365.png)


I tried renaming in them in the accessories tab on homebridge config UI as well as from within the home app.

I assume renaming these is only actualling changing a "friendly name" and that it might need to be done somewhere else.

I will work on the accessory dump and try to deliver it soon.

**Comment by davewehr** [comment]
Here is the dump:

{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"homebridge.io","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"homebridge","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Homebridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"CC:22:3D:E3:CE:30","description":"Serial Number"},{"iid":7,"type":"00000052-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"0.4.53","description":"Firmware Revision"}],"primary":false,"hidden":false},{"iid":2000000008,"type":"49FB9D4D-0FEA-4BF1-8FA6-E7B18AB86DCE","characteristics":[{"iid":9,"type":"77474A2F-FA98-485E-97BE-4762458774D8","perms":["pr","ev"],"format":"uint8","value":0,"description":"State","maxValue":1,"minValue":0,"minStep":1},{"iid":10,"type":"FD9FE4CC-D06F-4FFE-96C6-595D464E1026","perms":["pr","ev"],"format":"string","value":"1.0","description":"Version"},{"iid":11,"type":"5819A4C2-E1B0-4C9D-B761-3EB1AFF43073","perms":["pr","pw","ev"],"format":"data","valpi@raspberrypi:~ $

**Comment by NorthernMan54** [comment]
Tks for the dump, very helpful in resolving

As a workaround I changed the plugin logic to remove the duplicate records causing the error so that the Alexa parser will work.  And she should now see all your devices.

You should be good to go now

**Comment by davewehr** [comment]
Wow I appreciate the response.  Such a great community when the author of a plugin writes an update quick to help someone out!

Well I installed the updated and restarted but I’m getting similar errors and the same result (no devices added).

**Comment by NorthernMan54** [comment]
Can you share the log entry again, I had changed the error message, and want to what it says now.

**Comment by davewehr** [comment]
Is this attachment sufficient?

**Comment by NorthernMan54** [comment]
That was blank

I’m just looking for the ERROR lines when you ask Alexa to discover devices

**Comment by davewehr** [comment]
Sorry about that, I was trying to reply from my phone.

Here is a fresh log of the errors:

`[3/26/2020, 9:44:33 AM] [Alexa] WARNING: Duplicate device name Dew Point
[3/26/2020, 9:44:33 AM] [Alexa] WARNING: Duplicate device name Rain
[3/26/2020, 9:44:33 AM] [Alexa] WARNING: Duplicate device name Snow
[3/26/2020, 9:44:33 AM] [Alexa] WARNING: Duplicate device name Visibility: 14 km
[3/26/2020, 9:44:33 AM] [Alexa] WARNING: Duplicate device name Occupancy
[3/26/2020, 9:44:33 AM] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Dew Point
[3/26/2020, 9:44:33 AM] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Snow
[3/26/2020, 9:44:33 AM] [Alexa] ERROR: Parsing failed, removing duplicate endpointID => Visibility: 14 km
[3/26/2020, 9:44:33 AM] [Alexa] alexaDiscovery - returned 29 devices`

**Comment by NorthernMan54** [comment]
I was looking at the server logs, is your account dave.wehr?

Have you asked your Alexa to discover devices again this morning?  I haven’t seen one since the 25 @ 13:23 GMT

**Comment by davewehr** [comment]
I triggered device discovery via the app but did not ask verbally. I just asked her now, and I don't see any new devices added. 

Yes, my account username for homebridge.ca is 'dave.wehr'

**Comment by bruesche** [comment]
Hi there, I have the same problem. Everything is green on homebridge.ca and at the Startup from my Homebridge the alexaDiscovery find 46 Devices. But Alexa can‘t find Andy devices. Tried Alexa Discovery with App an with Voice. Can you help?
Mär 27 13:51:09 raspberrypi homebridge[29091]: }
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Discokugel
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Flurlampe
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Kugel
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Kugel Sofa
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Kugel Tisch
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Küchen TV
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Küchenlicht
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Multimedia
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name OPEN Schild
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Schlafzimmer TV
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] WARNING: Duplicate device name Wasserfall Effekt
Mär 27 13:51:26 raspberrypi homebridge[29091]: [2020-3-27 13:51:26] [Alexa] alexaDiscovery - returned 46 devices

**Comment by bruesche** [comment]
Hi, tried to uninstall the Plugin and install it new. Everything Sems fine. Connection to cloudservice is ok (Alexa connector closed). On homebridge.ca everything is Green lighted und the timestamps a new. Only in the start log is something which I did‘t undestand 

Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Kugel Tisch
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Discokugel
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Unknown 5
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Küchen TV
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Küchenlicht
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory OPEN Schild
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Kugel
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Flurlampe
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Wasserfall Effekt
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Kugel Sofa
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Schlafzimmer TV
Mär 27 18:47:41 raspberrypi homebridge[31706]: Failed to find plugin to handle accessory Multimedia


This are the devices for Alexa und After That the devices for plattform Alexa are duplicate (See post befor)

Hope ist helps...

**Comment by NorthernMan54** [comment]
@davewehr I'm working on another update to resolve this, stay tuned

**Comment by NorthernMan54** [comment]
@davewehr @bruesche Please update to the latest and try again.

**Comment by davewehr** [comment]
I think it's worse--now I get a lot of red error text and then the whole service restarted--in sort of a loop over and over again:

`[3/28/2020, 4:03:14 PM] Homebridge is running on port 51084.
[3/28/2020, 4:03:30 PM] [Alexa] WARNING: Duplicate device name Dew Point
[3/28/2020, 4:03:30 PM] [Alexa] WARNING: Duplicate device name Rain
[3/28/2020, 4:03:30 PM] [Alexa] WARNING: Duplicate device name Snow
[3/28/2020, 4:03:30 PM] [Alexa] WARNING: Duplicate device name Visibility: 13 km
[3/28/2020, 4:03:30 PM] [Alexa] WARNING: Duplicate device name Wind Speed: 1.49 m/s
[3/28/2020, 4:03:30 PM] [Alexa] WARNING: Duplicate device name Occupancy
[3/28/2020, 4:03:30 PM] TypeError: this.log is not a function
    at /usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:139:12
    at Array.forEach (<anonymous>)
    at removeDuplicateEndpoints (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:137:13)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:119:40)
    at HAPNodeJSClient.HAPaccessories (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:163:3)
    at Object.alexaDiscovery (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:95:14)
    at HAPNodeJSClient.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/alexaActions.js:33:20)
    at HAPNodeJSClient.emit (events.js:311:20)
    at HAPNodeJSClient._discoveryEnd (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:149:8)
    at listOnTimeout (internal/timers.js:549:17)
[3/28/2020, 4:03:30 PM] Got SIGTERM, shutting down Homebridge...
[3/28/2020, 4:03:35 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[3/28/2020, 4:03:40 PM] [HB Supervisor] Restarting Homebridge...`

**Comment by NorthernMan54** [comment]
@davewehr A big oops on my part ( sorry about that), please update to the latest
