### ISSUE TITLE
Beta Testing Open for Natural Language for Door's and Windows and other enhancements

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-alexa#327]
Everyone, If you're interested in testing a new version with support for using natural language for Garage Doors and Blinds/Window Coverings, I have finished testing everything and am getting ready to release it to the world

You have see the details in the updated README here

https://github.com/NorthernMan54/homebridge-alexa/tree/inputController#garage-door-blinds-and-window-coverings

To install the test version please use this command to install, and add the option door=true or blinds=true to your config.json. To rollback to the current version, just use the normal homebridge-alexa install command

npm install -g homebridge-alexa@beta

Also included with the new version is a fix for issue #287 and Input Controls for TV's and initial efforts for TV Channel Changing.

**Comment by Zaphor88** [comment]
Hi.  I get the message "permission denied or repository does not exist.

npm install -g NorthernMan54/inputController is correct?

**Comment by NorthernMan54** [comment]
@Zaphor88 bad command on my part

npm install -g NorthernMan54/homebridge-alexa#inputController

**Comment by Zaphor88** [comment]
Hi,
I have set up my homebridge today so that I can use the config ui x hb service.
If I now use npm install -g NorthernMan54 / homebridge-alexa # inputController I get the 0.5.0 installed but the error occurs:

[2020-6-6 13:21:51] [Alexa] alexaDiscovery - returned 46 devices
[2020-6-6 13:21:51] Error: ENOENT: no such file or directory, open './Desktop/alexa.json'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:129:8)
    at HAPNodeJSClient.HAPaccessories (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:203:3)
    at Object.alexaDiscovery (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:95:14)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:36:20)
    at HAPNodeJSClient.emit (events.js:223:5)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:112:10)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:186:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

I saw that you made a change 2 days ago. can it be because of it?

**Comment by NorthernMan54** [comment]
Oops yeah

I had added the saving of the Alexa device discovery object to the desktop to help troubleshoot  TV functionality.

If you create a directory called Desktop, the error will go away

**Comment by Zaphor88** [comment]
Great it works.
Thank you.

**Comment by JonyBCN** [comment]
In Spanish works too?

**Comment by NorthernMan54** [comment]
Should work, but not 100% sure.  give it a try

**Comment by JonyBCN** [comment]
> Should work, but not 100% sure. give it a try

Updated, added "Blinds": "true" to the .json, and I have no errors. But unfortunately in Spanish it doesn't work. "The device does not support that action."

**Comment by NorthernMan54** [comment]
Tks,  just need Amazon to finish their side
