### ISSUE TITLE
Beta Test 0.5.0 Bug: Lamp switch auto on.

### ISSUE THREAD

**Issue by Zaphor88** [NorthernMan54/homebridge-alexa#341]
For a few days now, a lamp switch has been switched on again automatically when you have switched it off. The lamp itself remains off only the switch in the Alexa app comes on again after 1-2 seconds and the percentage display sometimes goes to 1%.

I have already deleted the lamp in alexa app and also in homebridge with cache. Everything without change.
When I install the homebridge-alexa version 0.4.72 the bug is gone. I therefore assume that it is a bug in the beta version.

In Homekit the bug is not there the lamp works as it should.

<details>
<summary>Debug Terminal</summary>
<br>

```

[2020-6-16 20:27:38] [Alexa] PowerController TurnOff CC:22:3D:E3:CE:30 undefined null
2020-06-16T18:27:42.568Z alexaLocal Emitting Alexa
2020-06-16T18:27:42.569Z alexaActions alexaMessage: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"552bc6ff-ff89-41bd-b295-147a11ffeb6b","correlationToken":"AAAAAAAAAQAi9sAycbVye4RCOtC6CMhN/AEAAAAAAAA1R1WZeEK1m5IMNpW4jw7I8fgj5rz7Fm+wMwvBr83E/WtvRPdComA/LCh4xb4+nAT/XdG6aPQ7NvoLjULKeBit1a0qB5jQ4BlN3jC3ZQY6Hx4f7bkAGe6UF3FWA3hPPtj8F4HXoPKsXNpmfFd3kEefNlmy+WBdiFdnplBeNRnPT07veu1L1EY0XUusoOh2jxRh+alAc1+Kyuk9jnN5sqFepMnev7Z0Exi/oYRw9oncbdaetnv72lEwx0lNsdWrAVzlBCgLXYvLLwy7cKbXL5QiElcPh+iYNYrqTbBqmKuT+c6l/EFnA1f26qdfbTypWjgHiko0O5wlD00cP9Kz53q+8N6x2B+ZmOR/PO4KHvlubo8WEk3L9lBlrVWI2f7YHAVgCpaG8ganBAXVkaD1NdqRGK0HZv6mHTybmXBRCzbx9PS3IEcjPKPxTiiA2U75sjG677lS9uLHMKMXgpTzt+wbXNklWBlBh5Bqdbj/c1A/CqLqhTkYtM5x3SqkYBOxbolxearX5y4kqrK485uRh5Io3ukyuBGoSbtKhxxNzNUo1CKPkbfbifQqaztKxmceOmD8TozJjz/E9+1aW3kbLkk5szLQVOUOLsxTFlhthJklduA0vXj7EOrthutKfc7DwL1cLOC3Z+anRNMqvEH29Zx2Zk5e1bpopjHtIQ8P"},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1UdXlhTGFuIHVuZGVmaW5lZC1EZWNrZW5saWNodC0wMDAwMDA0My0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=","cookie":
{"TurnOn":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":10,\"value\":1}",
"AdjustPowerLevel":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":11}",
"ReportState":"[{\"interface\":\"Alexa.PowerController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":10},{\"interface\":\"Alexa.PowerLevelController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":11}]",
"BrightnessTurnOn":"true",
"SetPowerLevel":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":11}",
"TurnOff":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":10,\"value\":0}"}},
"payload":{}}}
2020-06-16T18:27:42.569Z alexaActions _HAPstatusByDeviceID-1 {
  body: '?id=101.10,101.11',
  interface: 'Alexa.PowerController,Alexa.PowerLevelController',
  deviceID: 'CC:22:3D:E3:CE:30',
  spacer: ','
}
2020-06-16T18:27:42.594Z alexaActions _HAPstatusByDeviceID-2 CC:22:3D:E3:CE:30 {
  characteristics: [
    { aid: 101, iid: 11, value: 100 },
    { aid: 101, iid: 10, value: false }
  ]
}
2020-06-16T18:27:42.595Z alexaActions alexaMessage: Response {
  "event": {
    "header": {
      "namespace": "Alexa",
      "name": "StateReport",
      "messageId": "552bc6ff-ff89-41bd-b295-147a11ffeb6b",
      "correlationToken": "AAAAAAAAAQAi9sAycbVye4RCOtC6CMhN/AEAAAAAAAA1R1WZeEK1m5IMNpW4jw7I8fgj5rz7Fm+wMwvBr83E/WtvRPdComA/LCh4xb4+nAT/XdG6aPQ7NvoLjULKeBit1a0qB5jQ4BlN3jC3ZQY6Hx4f7bkAGe6UF3FWA3hPPtj8F4HXoPKsXNpmfFd3kEefNlmy+WBdiFdnplBeNRnPT07veu1L1EY0XUusoOh2jxRh+alAc1+Kyuk9jnN5sqFepMnev7Z0Exi/oYRw9oncbdaetnv72lEwx0lNsdWrAVzlBCgLXYvLLwy7cKbXL5QiElcPh+iYNYrqTbBqmKuT+c6l/EFnA1f26qdfbTypWjgHiko0O5wlD00cP9Kz53q+8N6x2B+ZmOR/PO4KHvlubo8WEk3L9lBlrVWI2f7YHAVgCpaG8ganBAXVkaD1NdqRGK0HZv6mHTybmXBRCzbx9PS3IEcjPKPxTiiA2U75sjG677lS9uLHMKMXgpTzt+wbXNklWBlBh5Bqdbj/c1A/CqLqhTkYtM5x3SqkYBOxbolxearX5y4kqrK485uRh5Io3ukyuBGoSbtKhxxNzNUo1CKPkbfbifQqaztKxmceOmD8TozJjz/E9+1aW3kbLkk5szLQVOUOLsxTFlhthJklduA0vXj7EOrthutKfc7DwL1cLOC3Z+anRNMqvEH29Zx2Zk5e1bpopjHtIQ8P",
      "payloadVersion": "3"
    },
    "endpoint": {
      "endpointId": "Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1UdXlhTGFuIHVuZGVmaW5lZC1EZWNrZW5saWNodC0wMDAwMDA0My0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE="
    },
    "payload": {}
  },
  "context": {
    "properties": [
      {
        "namespace": "Alexa.PowerController",
        "name": "powerState",
        "value": "ON",
        "timeOfSample": "2020-06-16T18:27:42.595Z",
        "uncertaintyInMilliseconds": 500
      },
      {
        "namespace": "Alexa.PowerLevelController",
        "name": "powerLevel",
        "value": 0,
        "timeOfSample": "2020-06-16T18:27:42.595Z",
        "uncertaintyInMilliseconds": 500
      }
    ]
  }
}
2020-06-16T18:27:45.504Z alexaLocal Emitting Alexa
2020-06-16T18:27:45.504Z alexaActions alexaMessage: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"b265f6f1-f0b9-4c72-a2be-0306140efd2a","correlationToken":"AAAAAAAAAQAi9sAycbVye4RCOtC6CMhN/AEAAAAAAACq4+ZP4krKheEkY9pjwuoNJzRyx54UjcuRaYadU4gJE/asHGZlGIQLuER4KTLHkdn1G+1DQqEbwvHE2twgOJpIxoxsFGpN3V4kPT4z2q8hoqgXy98wt5sdtpOpTLpD0Ca4rytGzAnKA6uzezEb6k536YYPdBfoLI5dnc2Q1AkH1kPPDrbVJvbvPG2d8d6GKbswCkzSjrT7yDM6YlvSjFZzwr7FBTHCyp3mKrD/cDqvIoHBOiPM4HiXYcywhAAvSvKLh5aTaq26UkxHJDF+dulD81zI3XMvYyfP+X3XW3e7Q4uqNPTTtdh5Dr+V/B+0tA5oiI3PQYcJ9zQsTR+Mthr6TrlFzxzgYIEgtz3hPVPL0EIEECIAjen/DT53QWByioEvTrU9cji6xn72QyU4BUHEraJ6edDd72XC9vrvI+MpoyKlbQRfQyxe5auZU9wh1DPBgkhzUaVxhrqbxJVYHuQR3rIygKBvbSJj+WtUzLABq+dtQZ/ktCUPVjq3joZ8QOlNyPLJOe/ZMZJJqzmLjLtmbG2Y8/7t3ZL5bGu/g0qh/Pg1Q2UZQ5IjYJw6tx48ABMLZv2awEbBPs+SmAyoKvLp252NgisShGSTHo8tWysMEvzLCAj/7YouOETT3ae1364pTvpOlRjg3Zb9MhETdlAlz7vBeBKIFCwND5pW"},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1UdXlhTGFuIHVuZGVmaW5lZC1EZWNrZW5saWNodC0wMDAwMDA0My0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=","cookie":{"TurnOn":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":10,\"value\":1}","AdjustPowerLevel":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":11}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":10},{\"interface\":\"Alexa.PowerLevelController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":11}]","BrightnessTurnOn":"true","SetPowerLevel":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":11}","TurnOff":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":101,\"iid\":10,\"value\":0}"}},"payload":{}}}
2020-06-16T18:27:45.505Z alexaActions _HAPstatusByDeviceID-1 {
  body: '?id=101.10,101.11',
  interface: 'Alexa.PowerController,Alexa.PowerLevelController',
  deviceID: 'CC:22:3D:E3:CE:30',
  spacer: ','
}
2020-06-16T18:27:45.526Z alexaActions _HAPstatusByDeviceID-2 CC:22:3D:E3:CE:30 {
  characteristics: [
    { aid: 101, iid: 11, value: 100 },
    { aid: 101, iid: 10, value: false }
  ]
}
2020-06-16T18:27:45.527Z alexaActions alexaMessage: Response {
  "event": {
    "header": {
      "namespace": "Alexa",
      "name": "StateReport",
      "messageId": "b265f6f1-f0b9-4c72-a2be-0306140efd2a",
      "correlationToken": "AAAAAAAAAQAi9sAycbVye4RCOtC6CMhN/AEAAAAAAACq4+ZP4krKheEkY9pjwuoNJzRyx54UjcuRaYadU4gJE/asHGZlGIQLuER4KTLHkdn1G+1DQqEbwvHE2twgOJpIxoxsFGpN3V4kPT4z2q8hoqgXy98wt5sdtpOpTLpD0Ca4rytGzAnKA6uzezEb6k536YYPdBfoLI5dnc2Q1AkH1kPPDrbVJvbvPG2d8d6GKbswCkzSjrT7yDM6YlvSjFZzwr7FBTHCyp3mKrD/cDqvIoHBOiPM4HiXYcywhAAvSvKLh5aTaq26UkxHJDF+dulD81zI3XMvYyfP+X3XW3e7Q4uqNPTTtdh5Dr+V/B+0tA5oiI3PQYcJ9zQsTR+Mthr6TrlFzxzgYIEgtz3hPVPL0EIEECIAjen/DT53QWByioEvTrU9cji6xn72QyU4BUHEraJ6edDd72XC9vrvI+MpoyKlbQRfQyxe5auZU9wh1DPBgkhzUaVxhrqbxJVYHuQR3rIygKBvbSJj+WtUzLABq+dtQZ/ktCUPVjq3joZ8QOlNyPLJOe/ZMZJJqzmLjLtmbG2Y8/7t3ZL5bGu/g0qh/Pg1Q2UZQ5IjYJw6tx48ABMLZv2awEbBPs+SmAyoKvLp252NgisShGSTHo8tWysMEvzLCAj/7YouOETT3ae1364pTvpOlRjg3Zb9MhETdlAlz7vBeBKIFCwND5pW",
      "payloadVersion": "3"
    },
    "endpoint": {
      "endpointId": "Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1UdXlhTGFuIHVuZGVmaW5lZC1EZWNrZW5saWNodC0wMDAwMDA0My0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE="
    },
    "payload": {}
  },
  "context": {
    "properties": [
      {
        "namespace": "Alexa.PowerController",
        "name": "powerState",
        "value": "ON",
        "timeOfSample": "2020-06-16T18:27:45.527Z",
        "uncertaintyInMilliseconds": 500
      },
      {
        "namespace": "Alexa.PowerLevelController",
        "name": "powerLevel",
        "value": 0,
        "timeOfSample": "2020-06-16T18:27:45.527Z",
        "uncertaintyInMilliseconds": 500
      }
    ]
  }
}
```
</details>

**Comment by NorthernMan54** [comment]
Tks for sharing a detailed log entry.  Let me look into this further.

**Comment by Zaphor88** [comment]
hey you. the bug with the lamp is fixed. great thanks.
Now I have 6 lamps that no longer respond. you can already keep the lamps on but the startus cannot be queried.

<details open>
<summary>Debug Terminal</summary>
<br>
2020-06-17T04:44:08.310Z alexaLocal Emitting Alexa
2020-06-17T04:44:08.310Z alexaActions alexaMessage: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"142c73ed-6a29-4fb8-a9b0-c74d599c7848","correlationToken":"AAAAAAAAAQAx+hWLisTrcciVDIZdLmcy/AEAAAAAAACsepyLI1+MUCWlQba2rNTboFIRHBG5MzC8uAyP7rmeyWgTqZEyYVGmsMCZNOoqrjXSEakcpEOgV4SP3g+HmnCt3boBbeY2Vq/Eh5QA/a0r0xINp1haSKfdKJL72FNxbiLvisszrv+5PKLw9iRY1vN5j3fecEaxQ6dxqMnfsK9YWgTI9nYtT2hxDJ0xa3e4xU84qt+0oqfbJUOIZt3WA8QXaTTfV6xJLmyBE3sCnazollA6L68McOU+FXC/cwsfgrL0O9HkSlns6qgha9Z3udhTOOXDUWf5tDa+VezcahbcorqYuyPYY6XPOvzHeTVLPbBRgDWLOOq+Ng4f6frBgjWKiSrg/vw9XFzMqHdXgzl+ZQfJA2YXf/sMtS2qmXM523IhX9guK29iQNA+tlhBSgLbLA496HwQHMtZS8jonZmzOMR6ztdS3mka9UMg0+s8vLe1KJ6opfvPezuE0JLdofUMjdkXj/j5xsk7PGQWRwG8rpnJSDwJL/5KqpcRM1sBDMMCLNbXWrosfEZwfiTTLZLp5Zm7+IyJW0EoKaTqG01Kj7S9C4kAnS7zw9/T9sJq6WGwQBTAtoopwcbvVkY6obSNWbKbr2k2DkhGE7CaonGySuMpf7jnXK4QfWL24GC1J8zUrQe9YKl+CGnjCzZxPq2Oh2KDzDs/EcFihrYX"},"endpoint":{"endpointId":"Q0M6MjI6M0Q6RTM6Q0U6MzAtSG9tZWJyaWRnZS1NYWdpY0hvbWUtRmx1cmxpY2h0LTAwMDAwMDQzLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==","cookie":{"TurnOn":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":7,\"iid\":10,\"value\":1}","AdjustPowerLevel":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":7,\"iid\":13}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":7,\"iid\":10},{\"interface\":\"Alexa.PowerLevelController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":7,\"iid\":13},{\"interface\":\"Alexa.ColorController\",\"deviceID\":\"CC:22:3D:E3:CE:30\",\"hue\":{\"aid\":7,\"iid\":11},\"saturation\":{\"aid\":7,\"iid\":12},\"brightness\":{\"aid\":7,\"iid\":13},\"on\":{\"aid\":7,\"iid\":10}}]","BrightnessTurnOn":"true","SetPowerLevel":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":7,\"iid\":13}","SetColor":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"hue\":{\"aid\":7,\"iid\":11},\"saturation\":{\"aid\":7,\"iid\":12},\"brightness\":{\"aid\":7,\"iid\":13},\"on\":{\"aid\":7,\"iid\":10}}","TurnOff":"{\"deviceID\":\"CC:22:3D:E3:CE:30\",\"aid\":7,\"iid\":10,\"value\":0}"}},"payload":{}}}
2020-06-17T04:44:08.311Z alexaActions _HAPstatusByDeviceID-1 {
  body: '?id=7.10,7.13,7.11,7.12,7.13',
  interface: 'Alexa.PowerController,Alexa.PowerLevelController,Alexa.ColorController',
  deviceID: 'CC:22:3D:E3:CE:30',
  spacer: ',',
  elements: [
    { interface: 'Alexa.PowerController', aid: 7, iid: 10 },
    { interface: 'Alexa.PowerLevelController', aid: 7, iid: 13 },
    {
      interface: 'Alexa.ColorController',
      hue: [Object],
      saturation: [Object],
      brightness: [Object]
    }
  ]
}
2020-06-17T04:44:08.335Z alexaActions _HAPstatusByDeviceID-2 CC:22:3D:E3:CE:30 {
  characteristics: [
    { aid: 7, iid: 10, value: false },
    { aid: 7, iid: 13, value: 0 },
    { aid: 7, iid: 11, value: 0 },
    { aid: 7, iid: 12, value: 0 },
    { aid: 7, iid: 13, value: 0 }
  ]
}
(node:1491) UnhandledPromiseRejectionWarning: ReferenceError: _round is not defined
    at _getValue (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/messages.js:1220:14)
    at /usr/local/lib/node_modules/homebridge-alexa/lib/parse/messages.js:127:20
    at Array.forEach (<anonymous>:null:null)
    at Object.stateToProperties (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/messages.js:55:25)
    at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:888:26
    at /usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:555:9
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:610:7)
    at Request._callback (/usr/local/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:146:10)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

(node:1491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
</details>

**Comment by NorthernMan54** [comment]
Just fixed this

Please update and try again

**Comment by Zaphor88** [comment]
Great everything works. Thank you.
