### ISSUE TITLE
ESOCKETTIMEDOUT?

### ISSUE THREAD

**Issue by famewolf** [NorthernMan54/homebridge-alexa#394]
I keep seeing this error:

[12/12/2020, 11:37:14] [Alexa] PowerController TurnOff B8:27:EB:FD:D7:D8 undefined Error: 
undefined Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false,
  attempts: 5
}

**Comment by NorthernMan54** [comment]
Update to the latest version, and ask Alexa to discover devices again.
