### ISSUE TITLE
Can't add new device...

### ISSUE THREAD

**Issue by bmbking56** [NorthernMan54/homebridge-alexa#40]
Sorry, I could not add new homebridge device ...and I send debug mode error log.
If you teli me what's wrong , I'm happy.
Sorry I'm not good at command line .
And if it's OK , pls tell me how to join homebridgeteam.slack(need invitation?).
 
[2018-1-2 06:00:37] Loaded plugin: homebridge-bravia
[2018-1-2 06:00:37] Registering platform 'homebridge-bravia.BraviaPlatform'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded plugin: homebridge-dummy
[2018-1-2 06:00:37] Registering accessory 'homebridge-dummy.DummySwitch'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded plugin: homebridge-mac-display
[2018-1-2 06:00:37] Registering accessory 'mac-display.DisplaySwitch'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded plugin: homebridge-milight
[2018-1-2 06:00:37] Registering platform 'homebridge-milight.MiLight'
[2018-1-2 06:00:37] ---
  ssdp-client discovering all IPs from interface lo0 +0ms
  ssdp-client discovering all IPs from interface en1 +1ms
  ssdp-client Will use interface en1 +0ms
  ssdp-client discovering all IPs from interface utun0 +1ms
[2018-1-2 06:00:37] Loaded plugin: homebridge-platform-wemo
[2018-1-2 06:00:37] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded plugin: homebridge-sonybraviatv
[2018-1-2 06:00:37] Registering accessory 'homebridge-sonybraviatv.SonyBraviaTV'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded plugin: homebridge-sonybraviatv-input
[2018-1-2 06:00:37] Registering accessory 'homebridge-sonybraviatv.SonyBraviaTV-input'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded plugin: homebridge-sonytvremote
[2018-1-2 06:00:37] Registering accessory 'homebridge-sonytvremote.SonyTV'
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loaded config.json with 2 accessories and 2 platforms.
[2018-1-2 06:00:37] ---
[2018-1-2 06:00:37] Loading 2 platforms...
[2018-1-2 06:00:37] [WeMo Platform] Initializing BelkinWeMo platform...
  ssdp-client discovering all IPs from interface lo0 +153ms
  ssdp-client discovering all IPs from interface en1 +0ms
  ssdp-client Will use interface en1 +0ms
  ssdp-client discovering all IPs from interface utun0 +1ms
[2018-1-2 06:00:37] [MiLight] Initializing MiLight platform...
[2018-1-2 06:00:37] [MiLight] Initializing platform accessory '1'...
[2018-1-2 06:00:37] [MiLight] Initializing platform accessory '2'...
[2018-1-2 06:00:37] [MiLight] Initializing platform accessory '3'...
[2018-1-2 06:00:37] Loading 2 accessories...
[2018-1-2 06:00:37] [テレビ] Initializing SonyBraviaTV accessory...
[2018-1-2 06:00:37] [Fernseher] Initializing SonyTV accessory...
Setup Payload:
X-HM://0023ISYWY64C9
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  ssdp not running +0ms
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at Server.listen (net.js:1508:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:163:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:601:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:129:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:10)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by NorthernMan54** [comment]
This log is showing that another copy of homebridge is running when trying to start in debug mode.  Stop the other copy of homebridge then try this.
