### ISSUE TITLE
Errors with Alexa Plugin restarting HB

### ISSUE THREAD

**Issue by vzlgdu** [NorthernMan54/homebridge-alexa#404]
Hi, every time I restart HB, I receive the following errors (see log); after this everithing seems to work. This happens always.

HB v1.2.5
Node.js v13.13.0
npm v6.14.4
Alexa Plugin v0.5.21

Stopping Node.js HomeKit Server...
[29/12/2020, 08:50:16] Got SIGTERM, shutting down Homebridge...
[29/12/2020, 08:50:16] TypeError: Cannot read property 'toString' of undefined
    at Object.eventMessage (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaMessages.js:592:47)
    at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:963:35
    at Array.forEach (<anonymous>)
    at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:953:10)
    at EventEmitter.emit (events.js:315:20)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
    at HAPNodeJSClient.emit (events.js:315:20)
    at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
homebridge.service: Main process exited, code=exited, status=143/n/a
Stopped Node.js HomeKit Server.
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
Started Node.js HomeKit Server.
pam_unix(sudo:session): session closed for user root

**Comment by NorthernMan54** [comment]
Tks for reporting this.  I looked into this, and it is triggered by Homebridge being shutdown, not much can be done for this.

**Comment by NorthernMan54** [comment]
I made a change to trap that error and handle gracefully.  If you update to the latest it should no longer occur.

#393

**Comment by vzlgdu** [comment]
This is the result after the plugin update and after two restarts:

dic 30 16:07:21 homebridgea systemd[1]: Stopping Node.js HomeKit Server...
dic 30 16:07:21 homebridgea homebridge[18028]: [30/12/2020, 16:07:21] Got SIGTERM, shutting down Homebridge...
dic 30 16:07:21 homebridgea homebridge[18028]: ERROR: homebridge-alexa.alexaMessages.eventMessage TypeError: Cannot read property 'toString' of undefined
dic 30 16:07:21 homebridgea homebridge[18028]:     at Object.eventMessage (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaMessages.js:593:49)
dic 30 16:07:21 homebridgea homebridge[18028]:     at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:965:33
dic 30 16:07:21 homebridgea homebridge[18028]:     at Array.forEach (<anonymous>)
dic 30 16:07:21 homebridgea homebridge[18028]:     at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:955:10)
dic 30 16:07:21 homebridgea homebridge[18028]:     at EventEmitter.emit (events.js:315:20)
dic 30 16:07:21 homebridgea homebridge[18028]:     at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
dic 30 16:07:21 homebridgea homebridge[18028]:     at HAPNodeJSClient.emit (events.js:315:20)
dic 30 16:07:21 homebridgea homebridge[18028]:     at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
dic 30 16:07:21 homebridgea homebridge[18028]:     at EventEmitter.emit (events.js:315:20)
dic 30 16:07:21 homebridgea homebridge[18028]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
dic 30 16:07:21 homebridgea homebridge[18028]: [30/12/2020, 16:07:21] TypeError: Cannot read property 'event' of undefined
dic 30 16:07:21 homebridgea homebridge[18028]:     at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:971:24
dic 30 16:07:21 homebridgea homebridge[18028]:     at Array.forEach (<anonymous>)
dic 30 16:07:21 homebridgea homebridge[18028]:     at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:955:10)
dic 30 16:07:21 homebridgea homebridge[18028]:     at EventEmitter.emit (events.js:315:20)
dic 30 16:07:21 homebridgea homebridge[18028]:     at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
dic 30 16:07:21 homebridgea homebridge[18028]:     at HAPNodeJSClient.emit (events.js:315:20)
dic 30 16:07:21 homebridgea homebridge[18028]:     at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
dic 30 16:07:21 homebridgea homebridge[18028]:     at EventEmitter.emit (events.js:315:20)
dic 30 16:07:21 homebridgea homebridge[18028]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
dic 30 16:07:21 homebridgea homebridge[18028]:     at Socket.emit (events.js:327:22)
dic 30 16:07:26 homebridgea systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
dic 30 16:07:26 homebridgea systemd[1]: Stopped Node.js HomeKit Server.
dic 30 16:07:26 homebridgea systemd[1]: homebridge.service: Unit entered failed state.
dic 30 16:07:26 homebridgea systemd[1]: homebridge.service: Failed with result 'exit-code'.
dic 30 16:07:26 homebridgea systemd[1]: Started Node.js HomeKit Server.

**Comment by NorthernMan54** [comment]
Tks, let me look into this further

**Comment by vzlgdu** [comment]
Hi, today after a restart, alway the same error. Are there news?

Stopping Node.js HomeKit Server...
[30/1/2021, 10:08:27] Got SIGTERM, shutting down Homebridge...
ERROR: homebridge-alexa.alexaMessages.eventMessage TypeError: Cannot read property 'toString' of undefined
    at Object.eventMessage (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaMessages.js:593:49)
    at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:965:33
    at Array.forEach (<anonymous>)
    at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:955:10)
    at EventEmitter.emit (events.js:315:20)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
    at HAPNodeJSClient.emit (events.js:315:20)
    at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[30/1/2021, 10:08:27] TypeError: Cannot read property 'event' of undefined
    at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:971:24
    at Array.forEach (<anonymous>)
    at alexaHome.alexaEvent (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:955:10)
    at EventEmitter.emit (events.js:315:20)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:48:22)
    at HAPNodeJSClient.emit (events.js:315:20)
    at HAPNodeJSClient._reconnectServer (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:309:8)
    at EventEmitter.emit (events.js:315:20)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:90:24)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
homebridge.service: Main process exited, code=exited, status=143/n/a
Stopped Node.js HomeKit Server.
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
Started Node.js HomeKit Server.

**Comment by vzlgdu** [comment]
Sorry, I dont't understand your answare; is there a patch? should I download a new plugin (I've 0.5.25) with HB 1.2.5, and Node 13.13.0?
What is the meaning of "Fix for #404"?
Please, let me know.
Thanks

**Comment by NorthernMan54** [comment]
In #404 I commented out the debug line generating this message

ERROR: homebridge-alexa.alexaMessages.eventMessage TypeError: Cannot read property 'toString' of undefined
at Object.eventMessage (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaMessages.js:593:49)
at /usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:965:33
