### ISSUE TITLE
Getting "[Alexa] ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README." after updating to 0.5.21, 0.5.22

### ISSUE THREAD

**Issue by krharrison1** [NorthernMan54/homebridge-alexa#405]
Upgraded to 0.5.21 yesterday and found the "issue with your installation" error is now appearing in the logs. Tried disabling/reenabling alexa skill, restarting homebridge, no effect. Don't have multiple copies of homebridge-alexa on my network and am not using VPN. Upgraded to 0.5.22 today and same situation - Alexa says my homebridge-alexa devices are not responding and won't re-discover any homebridge-alexa devices if I remove them. 

The only other error I can find in my log file is the "ERROR: uncaughtException: Cannot read property 'toString' of undefined" that's thrown when Homebridge shuts down. Everything else looks clean. 

I will probably roll back to an earlier version, unless there are some ideas on how to fix this? 
Thank you.

**Comment by NorthernMan54** [comment]
This is triggered by the plugin not being able to discover your homebridge instances, are they running in 'Insecure Mode'.  If you enable the debug config option more logging will be enabled for the discover phase.

**Comment by krharrison1** [comment]
Log file has this entry which I believe means it's running in insecure mode:
HB Supervisor] Starting Homebridge with extra flags: -I

I turned debugging on in the homebridge-alexa options, and this is the first error that appears in the log file
2020-12-30T18:48:37.301Z alexaLocal ERROR: connect ECONNREFUSED 35.169.132.61:1883 ->  ECONNREFUSED
2020-12-30T18:48:37.313Z alexaLocal offline

**Comment by krharrison1** [comment]
I rolled back to 0.5.20 but now I get this error in the log file:

[12/30/2020, 3:10:49 PM] [Alexa] alexaDiscovery - returned 5 devices
[12/30/2020, 3:10:49 PM] Error: EACCES: permission denied, open 'alexaDiscovery.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1328:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:136:10)
    at HAPNodeJSClient.HAPaccessories (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:207:3)
    at Object.alexaDiscovery (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:95:14)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:36:20)
    at HAPNodeJSClient.emit (events.js:315:20)
    at HAPNodeJSClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:116:10)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:190:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

So I've rolled forward to 0.5.22 again and getting the same error messages as mentioned earlier.

**Comment by NorthernMan54** [comment]
Stop homebridge / raspberrypi for 5 minutes and start again.  This message is triggered by too many restarts

2020-12-30T18:48:37.301Z alexaLocal ERROR: connect ECONNREFUSED 35.169.132.61:1883 -> ECONNREFUSED

**Comment by krharrison1** [comment]
Thanks, stopping everything and restarting fixed it. Can you tell me what is the limitation with the restarts (i.e. how many max within a certain period of time) so I can avoid it in the future?  Thanks again for providing this plugin.

**Comment by NorthernMan54** [comment]
More than twice in a minute will trigger the error, but it should restore service automatically after a few minutes.

This is for this error:
2020-12-30T18:48:37.301Z alexaLocal ERROR: connect ECONNREFUSED 35.169.132.61:1883 -> ECONNREFUSED
