### ISSUE TITLE
Homebridge 1.3.0-beta.47 "Not Responding" issues

### ISSUE THREAD

**Issue by tom-23** [NorthernMan54/homebridge-alexa#416]
Hi there,

When using the beta version of HomeBridge, devices with colour capabilities (it seems) appear as "device unresponsive" in the Alexa app. But when I try to control a device, it seems to work without any issues and the "device unresponsive" message seems to go but then appears shortly after. Other devices like On/Off switches and curtains seem to function without any issues.

Running the plugin in debug mode shows this response being sent back when trying to grab the state of an accessory with colour capabilities:
```json
{
  "event": {
    "header": {
      "namespace": "Alexa",
      "name": "ErrorResponse",
      "messageId": "c9d11d7d-7af7-4b01-8d6b-89fc9b118352",
      "correlationToken": "AAAAAAAAAQD4k1G47SODZOVFMLU7zxWu/AEAAAAAAAAVtjD6wl+tt7vh7CST57O58r797v0QK4GeszSypDtD3VigxDc91lVaKUGQvJx4mblHjtjn8EBj1KAOB4nuLcTMfhWAda/w5kHH7e0gfv3mDec1TZWIGF3BjG0xFukFvEREMy/heM/oVSA/jQlWPThxzT5Nc8EQChuGL0pmEua2L3fB2i+CXW9/VdtiWcbmB+X8dLN4PQhq2I7KgQEWfZ4q7hR/AZ2jHOLbSE9Kc6BgSMtF1agfXY60JVg7QflOsi5oRikMqMepvDL2y/Kj6cfUJcz8YCQbQnX8DKOIsf2qzdBgmVBAIPHyEyX9dNiHBau0aoggm1ni1ExiRoaFcX9GPqBa1C9mG+kqCWgSrC6yAYq7JhKG2eiF8Y1bpYA19Ga9C5xg4ZFdZ5DxLxMBs3Y6nZAaKlLmHOwtPjNzdrYw3tBtF9mbPxXyjGwkJQCaG3lGXkQSeF0U//Ys45Gm2A+8Jeyv+nYsT2VFx9fwIbxe6+myZcTRIT7ckeb29BtxLFGyVBeV68NLELsLjU9OYzv0K6OS3L0KRhXcbcz41t30jr+YV4sn4+Z4N+njn73wauBOGKzhamPYR7eK2TG8Qys9Ax8IBdcksekoXJbpFgXO5EOkozA4/RmHZHkG9odUILsfvBxsY4yuFmR6N9ApUB6tKX7db0n1IL2bAmHa",
      "payloadVersion": "3"
    },
    "endpoint": {
      "endpointId": "MEU6QTk6MTY6OUI6NTA6NzItaG9tZWJyaWRnZS1tcXR0dGhpbmctVG9tcyBMaWdodCBTdHJpcHMtMDAwMDAwNDMtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx"
    },
    "payload": {
      "type": "ENDPOINT_UNREACHABLE",
      "message": "ERROR: HB Instance not found"
    }
  }
}
```

Whereas a device, like a switch, seemed to return a normal response.

Here's my config:
```json
{
            "name": "Alexa",
            "username": "xxxx",
            "password": "xxxx",
            "pin": "031-45-154",
            "blind": true,
            "routines": true,
            "debug": true,
            "platform": "Alexa"
}
```
Edit: Tested the plugin using the HomeBridge 1.2.0 and everything seemed to work fine.

**Comment by NorthernMan54** [comment]
Tks for reporting this Tom, I'm in the process of validating my suite of plugins, and just getting all the pieces pulled together to tackle Alexa.

When you were running under Homebridge 1.3.0-beta.47, did you ask Alexa to discover devices again ?

**Comment by tom-23** [comment]
@NorthernMan54 Just asked Alexa to discover devices again, the plugin successfully discovered all my accessories and the Alexa app said there were no new accessories. Checking the devices in the Alexa app still shows the "device unresponsive" message.

**Comment by NorthernMan54** [comment]
And which plugin has the colour devices ?

**Comment by tom-23** [comment]
I'm using both [homebridge-mqttthing](https://github.com/arachnetech/homebridge-mqttthing) and [homebridge-tuya](https://github.com/iRayanKhan/homebridge-tuya) and both are resulting in the same issue.

**Comment by NorthernMan54** [comment]
Tks Tom

As an FYI, we a tracking the plugin status here

https://github.com/homebridge/homebridge/wiki/Homebridge-1.3.0-Release-Plugin-Testing-Status

**Comment by tom-23** [comment]
Thanks! I'll add homebridge-magichome-dynamic-platform to the list once we've finished validating the plugin against the beta version!

**Comment by NorthernMan54** [comment]
Something odd is going on here

I finally got to the updating the portion of my homebridge environment where I have colour bulbs attached to homebridge-hue and was not able to recreate your issue.  But when I did update the environment I found that after asking Alexa to discover devices, she found duplicates of my hue devices.  I went thru the duplicates and removed them, then asked Alexa to discover again.  After that I did the test, and was successful.  What's odd is only a couple of my hue bulbs were duplicates but all the other devices where not duplicated.

**Comment by tom-23** [comment]
@NorthernMan54 In addition to the bulbs issue, I have a motion sensor set up with a routine but the routine is never triggered when motion is detected. However, if I go into the motion sensor within the Alexa app, I can see that the sensor is triggering motion. You're definitely right. Something odd is going on here.

**Comment by tom-23** [comment]
I also just had this error pop up out of nowhere:

```
[05/02/2021, 16:50:50] [Alexa] PowerController TurnOn 0E:A9:16:9B:50:72 undefined Error: ERROR: HB Instance not found
    at /usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:131:18
    at _populateCache (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:193:5)
    at _mdnsLookup (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:126:5)
    at HAPNodeJSClient.HAPcontrolByDeviceID (/usr/local/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/HAPNodeJSClient.js:222:3)
    at alexaHome.alexaPowerController (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaActions.js:334:14)
    at EventEmitter.emit (events.js:315:20)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/alexaLocal.js:70:26)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-alexa/node_modules/mqtt/lib/client.js:410:12)
```

**Comment by NorthernMan54** [comment]
Ask Alexa to discover devices again

**Comment by tom-23** [comment]
She's telling me there are no more device to add. I had another look in the logs and also found this message popping up:
```[05/02/2021, 17:23:38] [Alexa] PowerController TurnOn 0E:A9:16:9B:50:72 undefined null```

This really weird. So when I go into the Alexa app, every device is now saying "Device is unresponsive" but when I tap on a device in the Alexa app (showing me the big "on" button etc), after 8 or so seconds the device will report its state and allow me to control it. The amount of time can vary btw. But when I press on the back button in the Alexa app, returning me to the group, some devices report to be "Device is unresponsive" again. I've updated both your plugin and the latest beta of HomeBridge (1.3.0-beta.53). Turning debugging on in the plugin config also shows me a lot more "ERROR: HB instance not found" messages.

**Comment by NorthernMan54** [comment]
Please keep in mind that the 'status' checking in the app creates a DOS on the backend at a user level, so if you have a large number of devices it will be slow or sluggish.

Can you check your devices in the Alexa app, and see if you have any duplicates ?  If you continue to get the 'ERROR: HB instance not found' it is likely from duplicate devices.  When I flipped to the latest homebridge beta I found that my hue devices duplicated themselves, and needed to clean them up.

**Comment by NorthernMan54** [comment]
@tom-23 Anything further from your side on the original issue with home bridge 1.3.0 ?

**Comment by tom-23** [comment]
I'm still having the same issue I'm afraid. The error message has changed after I changed Homebridge's port:
```
2021-02-21T14:15:38.710Z hapNodeJSClient Homebridge Status failed 192.168.1.1:51826 Status: 422  ?id=48.10,48.12,48.15,48.13,48.14,48.12 null {"status":-70410}
2021-02-21T14:15:38.712Z alexaActions alexaMessage: Response {
  "event": {
    "header": {
      "namespace": "Alexa",
      "name": "ErrorResponse",
      "messageId": "307eef23-aac9-46e7-889a-3310f32a0b23",
      "correlationToken": "AAAAAAAAAQCzFtVOnBBecDNoXCG/xr5O/AEAAAAAAAAcgSDQ1TRU4wsCwXXHe3nMVfJlGUcCEnAfBf61HPiBwDa916WZrzDqxa3Js5kgKD3q+h8V0rUsdEAP5kOmuCNkqcZ44EiW3UtW9gnmcua4e26D0/p+s6P/Tm1Dkv3LNnYEJIuTuJSNHWv3LUvy6Sp+o1AymmxNW/SQkntU4vRCBjqdEgJq+QV+gkN8cjm0v4VyAWcRRQNWTnrymMdtwolLNHcIjN1gbZa+MFPWc+dE75969jvEzapG3nV4ikgd+P0TrEb+q6yJSRfwubH5OH5nivgbUpEAMdQwIfgMPerbBeihoctg7c5Q9lWjhKEw3CtW4RAzHx7t6UdhOfP7gxLeGQvQ/jMLcESHQqNfS3qUcT/tlZkpEv2UadQzlkel54dozZ5GcQoQYiP42uYKLQ5FiE70u8W0HWCH9/5exk8sKVn38Z401c+auoiiTNVhy9xgqAs4Gxct9UH7C1TJUuAxclgZ1kVdL1inyBxYGc7hUmBT5sLOSqWSf+zpO3W9GJD4cCzNgw8+6k8KT/nCOEe65Pdp2jj7mBvdSNhJZkldeZa0mesJ3G2L/eTJmCRUCOw0L8BVe9eB8aOTC6uKmVhOrjBX3Dxu/1ia3M/S3Sv+U9t1uGdi+bJl6fD/hj9Ct/wF0GWirU1Ab25W4AivSzhqEJSDtz/8a92ytJbU",
      "payloadVersion": "3"
    },
    "endpoint": {
      "endpointId": "MEU6QTk6MTY6OUI6NTA6NzItaG9tZWJyaWRnZS1NYWdpY0hvbWUtQnVsYiAwNTA2NDktMDAwMDAwNDMtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx"
    },
    "payload": {
      "type": "ENDPOINT_UNREACHABLE",
      "message": "Homebridge status failed"
    }
  }
}
2021-02-21T14:15:38.841Z hapNodeJSClient HAP Device discovered HomeHB 2EA7
2021-02-21T14:15:38.852Z hapNodeJSClient HAP Device discovered Living Room TV 79E4
2021-02-21T14:15:41.677Z alexaLocal Emitting Alexa
2021-02-21T14:15:41.678Z alexaActions alexaMessage: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"a49554bc-b9f9-4c93-84c1-a06ce68d1a73","correlationToken":"AAAAAAAAAQCzFtVOnBBecDNoXCG/xr5O/AEAAAAAAAADsPe9hMpvdXYkjCxAG92OB00mlfjqroYRw+HvOZ9keY5QtnK24LafVtG7rln/I75+AiPwRFvJdizTS7vtRsV9DRYM5RPmu/qgTkoik3cR/sJDE7Sk/ZpVacX6xLBuX2S5GedrEGGfqAmYuDnOV7n5gn9jkOdHGmHzKbzam2KZlH2meEGSvDcHMrwCvmqyWQFcO0SEANN4YT81LnVjmOuZQwqrXcl+t/rqc+LyXQgG6bsg6bTNPukS8sZpR7rij+qYajkJdu9wj7BAoGHTaaa10IrBpYdDnMqoSKTDqzuAjSlsBTh2sbX15Uue350qCCRNqi+qr79aCtsH/kGY38jRn4rX/llOW75xiaPw/y6Fo2PbKtmNc1WbMU0ZuqrUI7yF9Zrz3zuML9wOluqrmaNqTfoSW7K0bVXLh7LZmDetwR7EYW/yuaQjbhB0rBPd8Sg/OvscvEggq++Kro58ywSfX2541R/GUXusk8MPQNXQfFLsM6uGujsbSHm5UCx9vPawXoZ7BghBFWK21GN07AL6iBCpw5EnPvMw+x9jQvEmnIvYwkMZcJxSVR4IVwsgcepmb4ELMMMi/3ewRx8E/ucOuE2Vv9Am0k5AAJ/G0NvbEoIXX5H6C8FspgLkYomwPf4Tb+/tynfwij3ndHr1ccB7w95SomJaLFfKBB3r"},"endpoint":{"endpointId":"MEU6QTk6MTY6OUI6NTA6NzItaG9tZWJyaWRnZS1NYWdpY0hvbWUtQnVsYiAwNTA2NDktMDAwMDAwNDMtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx","cookie":{"TurnOn":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":10,\"value\":1}","AdjustPowerLevel":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":12}","ReportState":"[{\"interface\":\"Alexa.PowerController\",\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":10},{\"interface\":\"Alexa.PowerLevelController\",\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":12},{\"interface\":\"Alexa.ColorTemperatureController\",\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":15},{\"interface\":\"Alexa.ColorController\",\"deviceID\":\"0E:A9:16:9B:50:72\",\"hue\":{\"aid\":48,\"iid\":13},\"saturation\":{\"aid\":48,\"iid\":14},\"brightness\":{\"aid\":48,\"iid\":12},\"on\":{\"aid\":48,\"iid\":10}}]","SetColorTemperature":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":15}","BrightnessTurnOn":"true","DecreaseColorTemperature":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":15}","SetPowerLevel":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":12}","SetColor":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"hue\":{\"aid\":48,\"iid\":13},\"saturation\":{\"aid\":48,\"iid\":14},\"brightness\":{\"aid\":48,\"iid\":12},\"on\":{\"aid\":48,\"iid\":10}}","IncreaseColorTemperature":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":15}","TurnOff":"{\"deviceID\":\"0E:A9:16:9B:50:72\",\"aid\":48,\"iid\":10,\"value\":0}"}},"payload":{}}}
2021-02-21T14:15:41.679Z alexaActions _HAPstatusByDeviceID-1 {
  body: '?id=48.10,48.12,48.15,48.13,48.14,48.12',
  interface: 'Alexa.PowerController,Alexa.PowerLevelController,Alexa.ColorTemperatureController,Alexa.ColorController',
  deviceID: '0E:A9:16:9B:50:72',
  spacer: ',',
  elements: [
    { interface: 'Alexa.PowerController', aid: 48, iid: 10 },
    { interface: 'Alexa.PowerLevelController', aid: 48, iid: 12 },
    { interface: 'Alexa.ColorTemperatureController', aid: 48, iid: 15 },
    {
      interface: 'Alexa.ColorController',
      hue: [Object],
      saturation: [Object],
      brightness: [Object]
    }
  ]
}
```

**Comment by AlexKusnezov** [comment]
same here, today I went from 1.2.5 to 1.3.1 (docker) and neither alexa nor google home have respose from devices

**Comment by NorthernMan54** [comment]
@tom-23 After changing ports did you discover devices again ? Asking Alexa to discover devices resets the links between the Alexa plugin and homebridge and is needed after making configuration changes in homebridge.  She may say no new devices, but the links between homebridge and Alexa would have been refreshed

@AlexKusnezov Please don't jump into an unrelated issue

**Comment by NorthernMan54** [comment]
Closing for lack of information
