### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-alexa

### ISSUE THREAD

**Issue by Samconboy** [NorthernMan54/homebridge-alexa#44]
Hi, I have homebridge installed, and homebridge-alexa also. However when starting homebridge I receive this error:

ERROR LOADING PLUGIN homebridge-alexa:
[Fri Jan 12 2018 11:43:16 GMT+0000 (UTC)] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-alexa/index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:142:14)
    at Array.forEach (native)
    at Server.str.replace.Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:138:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)

I had a look in the folder /usr/local/lib/node_modules/homebridge-alexa/ , but the index.js file is missing
from there.

Any help would be amazing thanks.

**Comment by NorthernMan54** [comment]
Please read the readme carefully.  This is not a plugin, but instructions to install a special version of homebridge that integrates with Alexa.

**Comment by Samconboy** [comment]
Do I need to remove my exisiting version of homebridge to run this?

**Comment by Samconboy** [comment]
fixed it now, did a complete reinstall without the original homebridge
