### ISSUE TITLE
Cannot read property 'RegisterPin' of undefined

### ISSUE THREAD

**Issue by khituras** [NorthernMan54/homebridge-alexa#445]
Hi,
I try to use this plugin as given from the HOOBS plugin registry. I hope that my question is still right here.

I get the setup working so far that I can discover my devices in the Alexa app and habe green light on all numbers at https://www.homebridge.ca except "6 - Date of last sensor event message".
The issue is that when I want to actually switch a light on and off via the Alex app, my HOOBS log shows the following error message:

```
May 02 15:32:05 hoobs hoobs[628]: TypeError: Cannot read property 'RegisterPin' of undefined
May 02 15:32:05 hoobs hoobs[628]:     at /home/hoobs/.hoobs/node_modules/hap-node-client/HAPNodeJSClient.js:131:14
May 02 15:32:05 hoobs hoobs[628]:     at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/hap-node-client/HAPNodeJSClient.js:194:7)
May 02 15:32:05 hoobs hoobs[628]:     at listOnTimeout (internal/timers.js:554:17)
May 02 15:32:05 hoobs hoobs[628]:     at processTimers (internal/timers.js:497:7)
May 02 15:32:05 hoobs hoobs[628]: Got SIGTERM, shutting down Bridge...
May 02 15:32:10 hoobs hoobs[628]: [Hue] goodbye
May 02 15:32:20 hoobs systemd[1]: Stopping HOOBS...
May 02 15:32:20 hoobs hoobs[628]: [HOOBS] Stopping server.
```

I thought that this could have something to do with the Homebridge PIN. But I haven't changed it and it reads "031-45-154" in my `config.json`. I tried to specify it anyway but to no avail.

What's curious is that I actually could switch on and off my light a few times after the very first try. But then the error appeared once and since then it appears immediately when trying (of course I did restarts of HOOBS and even of the whole Raspberry Pie after having the error).

Any idea what I should do?

Here is a accessory dump in case that would be helpful:

```hoobs@hoobs:~/.hoobs/etc $ curl -X PUT http://127.0.0.1:51826/accessories --header "Content-Type:Application/json" --header "authorization: 031-45-154"
{"accessories":[{"aid":1,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"HOOBS","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"HOOBS","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"HOOBS C438","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"D9:9D:72:F4:6B:3F","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"1.2.3","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"A2","iid":2000000012,"characteristics":[{"type":"37","iid":13,"value":"1.1.0","perms":["pr"],"description":"Version","format":"string","maxLen":64}]}]},{"aid":79,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"homebridge-alexa","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"Default-Model","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Alexa","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"hoobs","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"0.5.34","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"80","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Alexa","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"6A","iid":10,"value":0,"perms":["ev","pr"],"description":"Contact Sensor State","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]}]}]},{"aid":2,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Xiaomi","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"23","iid":5,"value":"BB7","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"21","iid":4,"value":"roborock.vacuum.s5e","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"52","iid":7,"value":"3.5.8_1410","perms":["pr"],"description":"Firmware Revision","format":"string"},{"type":"30","iid":6,"value":"R0514S94800974","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64}]},{"type":"40","iid":8,"characteristics":[{"type":"23","iid":9,"value":"BB7","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":10,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"},{"type":"29","iid":11,"value":33.333333333333336,"perms":["ev","pr","pw"],"description":"Rotation Speed","format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":16.666666666666668},{"type":"AC","iid":12,"value":0,"perms":["ev","pr"],"description":"Filter Change Indication","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"AB","iid":13,"value":44,"perms":["ev","pr"],"description":"Filter Life Level","format":"float","minValue":0,"maxValue":100,"minStep":1}],"primary":true,"linked":[14,19,22,59,28,31,62,37,41,45,49]},{"type":"96","iid":14,"characteristics":[{"type":"23","iid":15,"value":"BB7 Battery","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"8F","iid":17,"value":1,"perms":["ev","pr"],"description":"Charging State","format":"uint8","minValue":0,"maxValue":2,"minStep":1,"valid-values":[0,1,2]},{"type":"79","iid":18,"value":0,"perms":["ev","pr"],"description":"Status Low Battery","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"68","iid":16,"value":99,"perms":["ev","pr"],"description":"Battery Level","format":"uint8","unit":"percentage","minValue":0,"maxValue":100,"minStep":1}]},{"type":"86","iid":19,"characteristics":[{"type":"23","iid":20,"value":"BB7 Dock","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"71","iid":21,"value":1,"perms":["ev","pr"],"description":"Occupancy Detected","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]}]},{"type":"49","iid":22,"characteristics":[{"type":"23","iid":23,"value":"sauge das Schlafzimmer","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":24,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"}]},{"type":"49","iid":59,"characteristics":[{"type":"23","iid":60,"value":"sauge die Küche","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":61,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"}]},{"type":"49","iid":28,"characteristics":[{"type":"23","iid":29,"value":"sauge das Wohnzimmer","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":30,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"}]},{"type":"49","iid":31,"characteristics":[{"type":"23","iid":32,"value":"sauge den Flur","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":33,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"}]},{"type":"49","iid":62,"characteristics":[{"type":"23","iid":63,"value":"sauge das Badezimmer","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"25","iid":64,"value":0,"perms":["ev","pr","pw"],"description":"On","format":"bool"}]},{"type":"BA","iid":37,"characteristics":[{"type":"23","iid":38,"value":"Care indicator sensors","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"AC","iid":39,"value":0,"perms":["ev","pr"],"description":"Filter Change Indication","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"AB","iid":40,"value":44,"perms":["ev","pr"],"description":"Filter Life Level","format":"float","minValue":0,"maxValue":100,"minStep":1}]},{"type":"BA","iid":41,"characteristics":[{"type":"23","iid":42,"value":"Care indicator filter","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"AC","iid":43,"value":0,"perms":["ev","pr"],"description":"Filter Change Indication","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"AB","iid":44,"value":68,"perms":["ev","pr"],"description":"Filter Life Level","format":"float","minValue":0,"maxValue":100,"minStep":1}]},{"type":"BA","iid":45,"characteristics":[{"type":"23","iid":46,"value":"Care indicator side brush","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"AC","iid":47,"value":0,"perms":["ev","pr"],"description":"Filter Change Indication","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"AB","iid":48,"value":76,"perms":["ev","pr"],"description":"Filter Life Level","format":"float","minValue":0,"maxValue":100,"minStep":1}]},{"type":"BA","iid":49,"characteristics":[{"type":"23","iid":50,"value":"Care indicator main brush","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"AC","iid":51,"value":0,"perms":["ev","pr"],"description":"Filter Change Indication","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"AB","iid":52,"value":84,"perms":["ev","pr"],"description":"Filter Life Level","format":"float","minValue":0,"maxValue":100,"minStep":1}]}]},{"aid":74,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"dresden elektronik","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"deCONZ","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Phoscon-GW","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"00212EFFFF060A9B","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"2.10.4","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"00000012-0000-1000-8000-656261617577","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Phoscon-GW","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"00000024-0000-1000-8000-656261617577","iid":10,"value":5,"perms":["pr","ev","pw"],"description":"Heartrate","format":"uint16","unit":"seconds","minValue":1,"maxValue":30},{"type":"00000023-0000-1000-8000-656261617577","iid":11,"value":"Sun May 02 2021 15:41:22","perms":["pr","ev"],"description":"Last Updated","format":"string"},{"type":"0000002F-0000-1000-8000-656261617577","iid":12,"value":0.4,"perms":["pr","ev","pw"],"description":"Transition Time","format":"float","unit":"seconds","minValue":0,"maxValue":3600,"minStep":0.1},{"type":"00000058-0000-1000-8000-656261617577","iid":13,"value":0,"perms":["pr","ev","pw"],"description":"Restart","format":"bool"}]}]},{"aid":80,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Signify Netherlands B.V.","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"LCT007","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Tischlampe","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"001788010230A40C","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"5.130.1.30000","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"43","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Tischlampe","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"8","iid":11,"value":100,"perms":["ev","pr","pw"],"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"00000057-0000-1000-8000-656261617577","iid":12,"value":0,"perms":["pr","ev","pw"],"description":"Brightness Change","format":"int","minValue":-20,"maxValue":20},{"type":"CE","iid":13,"value":185,"perms":["ev","pr","pw"],"description":"Color Temperature","format":"int","minValue":153,"maxValue":500,"minStep":1},{"type":"144","iid":14,"value":"AQYBAQsCAQEAAAEGAQENAgEC","perms":["pr"],"description":"Supported Characteristic Value Transition Configuration","format":"tlv8"},{"type":"24B","iid":16,"value":0,"perms":["ev","pr"],"description":"Characteristic Value Active Transition Count","format":"uint8"},{"type":"13","iid":17,"value":61,"perms":["ev","pr","pw"],"description":"Hue","format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1},{"type":"2F","iid":18,"value":7,"perms":["ev","pr","pw"],"description":"Saturation","format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"00000059-0000-1000-8000-656261617577","iid":19,"value":0,"perms":["pr","ev","pw"],"description":"Color Loop","format":"bool"},{"type":"0000006C-0000-1000-8000-656261617577","iid":20,"value":25,"perms":["pr","ev","pw"],"description":"Color Loop Speed","format":"uint16","unit":"seconds","minValue":1,"maxValue":65534},{"type":"77","iid":21,"value":0,"perms":["ev","pr"],"description":"Status Fault","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"00000021-0000-1000-8000-656261617577","iid":22,"value":"/lights/1","perms":["pr"],"description":"Resource","format":"string"},{"type":"00000060-0000-1000-8000-656261617577","iid":23,"value":"Thu Apr 29 2021 07:16:58","perms":["pr","ev"],"description":"Last Boot","format":"string"},{"type":"00000061-0000-1000-8000-656261617577","iid":24,"value":"Sun May 02 2021 15:40:00","perms":["pr","ev"],"description":"Last Seen","format":"string"},{"type":"25","iid":10,"value":1,"perms":["ev","pr","pw"],"description":"On","format":"bool"},{"type":"143","iid":15,"value":"","perms":["pr","pw","wr"],"description":"Characteristic Value Transition Control","format":"tlv8"}]}]},{"aid":81,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Signify Netherlands B.V.","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"LCT007","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Bettlampe","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"00178801020A48B7","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"5.130.1.30000","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"43","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Bettlampe","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"8","iid":11,"value":61,"perms":["ev","pr","pw"],"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"00000057-0000-1000-8000-656261617577","iid":12,"value":0,"perms":["pr","ev","pw"],"description":"Brightness Change","format":"int","minValue":-20,"maxValue":20},{"type":"CE","iid":13,"value":153,"perms":["ev","pr","pw"],"description":"Color Temperature","format":"int","minValue":153,"maxValue":500,"minStep":1},{"type":"144","iid":14,"value":"AQYBAQsCAQEAAAEGAQENAgEC","perms":["pr"],"description":"Supported Characteristic Value Transition Configuration","format":"tlv8"},{"type":"24B","iid":16,"value":0,"perms":["ev","pr"],"description":"Characteristic Value Active Transition Count","format":"uint8"},{"type":"13","iid":17,"value":24,"perms":["ev","pr","pw"],"description":"Hue","format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1},{"type":"2F","iid":18,"value":66,"perms":["ev","pr","pw"],"description":"Saturation","format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"00000059-0000-1000-8000-656261617577","iid":19,"value":0,"perms":["pr","ev","pw"],"description":"Color Loop","format":"bool"},{"type":"0000006C-0000-1000-8000-656261617577","iid":20,"value":25,"perms":["pr","ev","pw"],"description":"Color Loop Speed","format":"uint16","unit":"seconds","minValue":1,"maxValue":65534},{"type":"77","iid":21,"value":0,"perms":["ev","pr"],"description":"Status Fault","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"00000021-0000-1000-8000-656261617577","iid":22,"value":"/lights/2","perms":["pr"],"description":"Resource","format":"string"},{"type":"00000060-0000-1000-8000-656261617577","iid":23,"value":"Tue Apr 06 2021 21:09:05","perms":["pr","ev"],"description":"Last Boot","format":"string"},{"type":"00000061-0000-1000-8000-656261617577","iid":24,"value":"Sun May 02 2021 15:40:00","perms":["pr","ev"],"description":"Last Seen","format":"string"},{"type":"25","iid":10,"value":1,"perms":["ev","pr","pw"],"description":"On","format":"bool"},{"type":"143","iid":15,"value":"","perms":["pr","pw","wr"],"description":"Characteristic Value Transition Control","format":"tlv8"}]}]},{"aid":82,"services":[{"type":"3E","iid":1,"characteristics":[{"type":"14","iid":2,"perms":["pw"],"description":"Identify","format":"bool"},{"type":"20","iid":3,"value":"Signify Netherlands B.V.","perms":["pr"],"description":"Manufacturer","format":"string","maxLen":64},{"type":"21","iid":4,"value":"LCT007","perms":["pr"],"description":"Model","format":"string","maxLen":64},{"type":"23","iid":5,"value":"Sofalampe","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"30","iid":6,"value":"001788010207E600","perms":["pr"],"description":"Serial Number","format":"string","maxLen":64},{"type":"52","iid":7,"value":"5.130.1.30000","perms":["pr"],"description":"Firmware Revision","format":"string"}]},{"type":"43","iid":8,"characteristics":[{"type":"23","iid":9,"value":"Sofalampe","perms":["pr"],"description":"Name","format":"string","maxLen":64},{"type":"8","iid":11,"value":39,"perms":["ev","pr","pw"],"description":"Brightness","format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"00000057-0000-1000-8000-656261617577","iid":12,"value":0,"perms":["pr","ev","pw"],"description":"Brightness Change","format":"int","minValue":-20,"maxValue":20},{"type":"CE","iid":13,"value":153,"perms":["ev","pr","pw"],"description":"Color Temperature","format":"int","minValue":153,"maxValue":500,"minStep":1},{"type":"144","iid":14,"value":"AQYBAQsCAQEAAAEGAQENAgEC","perms":["pr"],"description":"Supported Characteristic Value Transition Configuration","format":"tlv8"},{"type":"24B","iid":16,"value":0,"perms":["ev","pr"],"description":"Characteristic Value Active Transition Count","format":"uint8"},{"type":"13","iid":17,"value":27,"perms":["ev","pr","pw"],"description":"Hue","format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1},{"type":"2F","iid":18,"value":59,"perms":["ev","pr","pw"],"description":"Saturation","format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1},{"type":"00000059-0000-1000-8000-656261617577","iid":19,"value":0,"perms":["pr","ev","pw"],"description":"Color Loop","format":"bool"},{"type":"0000006C-0000-1000-8000-656261617577","iid":20,"value":25,"perms":["pr","ev","pw"],"description":"Color Loop Speed","format":"uint16","unit":"seconds","minValue":1,"maxValue":65534},{"type":"77","iid":21,"value":0,"perms":["ev","pr"],"description":"Status Fault","format":"uint8","minValue":0,"maxValue":1,"minStep":1,"valid-values":[0,1]},{"type":"00000021-0000-1000-8000-656261617577","iid":22,"value":"/lights/4","perms":["pr"],"description":"Resource","format":"string"},{"type":"00000060-0000-1000-8000-656261617577","iid":23,"value":"Fri Nov 27 2020 14:51:52","perms":["pr","ev"],"description":"Last Boot","format":"string"},{"type":"00000061-0000-1000-8000-656261617577","iid":24,"value":"Sun May 02 2021 15:40:00","perms":["pr","ev"],"description":"Last Seen","format":"string"},{"type":"25","iid":10,"value":1,"perms":["ev","pr","pw"],"description":"On","format":"bool"},{"type":"143","iid":15,"value":"","perms":["pr","pw","wr"],"description":"Characteristic Value Transition Control","format":"tlv8"}]}]}]}
```

**Comment by RyTsYdUp** [comment]
I'm experiencing the same issue. Not sure what the cause is.

If you turn on Alexa debug. Are you seeing the following errors: 
"type": "ENDPOINT_UNREACHABLE",
      "message": "Homebridge status failed"

**Comment by khituras** [comment]
Hi, thanks for the answer. I activated debug and indeed:

```
May 03 08:10:16 hoobs hoobs[589]: 2021-05-03T06:10:16.454Z alexaLocal Emitting Alexa
May 03 08:10:16 hoobs hoobs[589]: 2021-05-03T06:10:16.456Z alexaActions alexaMessage: {"directive":{"header":{"namespace":"Alexa","name":"ReportState","payloadVersion":"3","messageId":"f66317ec-698b-4179-ba78-6e2f58433342","correlationToken":"AAAAAAAAAQCJaTgJFuvl8NCbqOlfnXu5/AEAAAAAAADkWIaZOyIJJ5nWPkqCw5mwsS+4NeoHFbaA1sUCmbLQ67mSrVrfB+99PcWDq+uiIllt1rXFm0MimYgScJi5PvmjUreZvomhdK19r5MrjpLM7h15/XD7S4Yk7VnH/oJS8XBOH9qf0Wxl+8Tp5rk9nGwanrBhM1yHqjaWhTuhLzqRnbCT/K5nQvRGHyBWwdQlhIkXA8IbKXh4DqkGYJG3JyxD5ldEm/z17RNzNlBG5O16Pa+U2b5yyKYyDkUyYUgRwFwiW1MZMGRX1UDqTGLTsGIs8YCZ1kDMg+kBye1+pcyWhYQmJrrCGjK0jShdMn1M+RV87asq6qQKoAmB+i58m5poU90kBicHyvT2Cuu77CemwxQFbkGgH5+TJP1rpUNUpLnHgAGcofmEDAOv2HLdEd+COKYIp+LvZ4ZHWbqnQ6yLBSSjvS9lfuqnRx4kJfjucNDQUDucn6r8sm9NgGW8TGDCjy1+xv24RbzNv0zn2R4rvwZeoV++WeCmrIR99MA5bQTaaVeiRbWDPWPNgBNWlbtDjuFFslMg3JMjUo6niSwDf6dKaa0plVKXNks9dC6lpr+kTV0nEajdMbZw175rTWGtQh4XTquWRrTQ/7FsBzWZK/TDrrTe9EAmkvRmmQM7co1ATz3JmJXoglG7/2ODsYQ2VaNXo/ThTV4ROh+H"},"endpoint":{"endpointId":"RDk6OUQ6NzI6RjQ6NkI6M0YtSE9PQlMtU2lnbmlmeSBOZXRoZXJsYW5kcyBCLlYuLVRpc2NobGFtcGUtMDAwMDAwNDMtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx","cookie":{"TurnOn":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":10,\"value\":1}","AdjustPowerLevel":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":11}","ReportState":"[{\"interface\":\"Alexa.PowerLevelController\",\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":11},{\"interface\":\"Alexa.ColorTemperatureController\",\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":13},{\"interface\":\"Alexa.PowerController\",\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":10},{\"interface\":\"Alexa.ColorController\",\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"hue\":{\"aid\":75,\"iid\":17},\"saturation\":{\"aid\":75,\"iid\":18},\"brightness\":{\"aid\":75,\"iid\":11},\"on\":{\"aid\":75,\"iid\":10}}]","SetColorTemperature":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":13}","BrightnessTurnOn":"true","DecreaseColorTemperature":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":13}","SetPowerLevel":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":11}","SetColor":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"hue\":{\"aid\":75,\"iid\":17},\"saturation\":{\"aid\":75,\"iid\":18},\"brightness\":{\"aid\":75,\"iid\":11},\"on\":{\"aid\":75,\"iid\":10}}","IncreaseColorTemperature":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":13}","TurnOff":"{\"deviceID\":\"D9:9D:72:F4:6B:3F\",\"aid\":75,\"iid\":10,\"value\":0}"}},"payload":{}}}
May 03 08:10:16 hoobs hoobs[589]: 2021-05-03T06:10:16.459Z alexaActions _HAPstatusByDeviceID-1 {
May 03 08:10:16 hoobs hoobs[589]: body: '?id=75.11,75.13,75.10,75.17,75.18,75.11',
May 03 08:10:16 hoobs hoobs[589]: interface: 'Alexa.PowerLevelController,Alexa.ColorTemperatureController,Alexa.PowerController,Alexa.ColorController',
May 03 08:10:16 hoobs hoobs[589]: deviceID: 'D9:9D:72:F4:6B:3F',
May 03 08:10:16 hoobs hoobs[589]: spacer: ',',
May 03 08:10:16 hoobs hoobs[589]: elements: [
May 03 08:10:16 hoobs hoobs[589]: { interface: 'Alexa.PowerLevelController', aid: 75, iid: 11 },
May 03 08:10:16 hoobs hoobs[589]: { interface: 'Alexa.ColorTemperatureController', aid: 75, iid: 13 },
May 03 08:10:16 hoobs hoobs[589]: { interface: 'Alexa.PowerController', aid: 75, iid: 10 },
May 03 08:10:16 hoobs hoobs[589]: {
May 03 08:10:16 hoobs hoobs[589]: interface: 'Alexa.ColorController',
May 03 08:10:16 hoobs hoobs[589]: hue: [Object],
May 03 08:10:16 hoobs hoobs[589]: saturation: [Object],
May 03 08:10:16 hoobs hoobs[589]: brightness: [Object]
May 03 08:10:16 hoobs hoobs[589]: }
May 03 08:10:16 hoobs hoobs[589]: ]
May 03 08:10:16 hoobs hoobs[589]: }
May 03 08:10:16 hoobs hoobs[589]: 2021-05-03T06:10:16.482Z hapNodeJSClient Homebridge Status failed 192.168.178.79:51826 Status: 422  ?id=75.11,75.13,75.10,75.17,75.18,75.11 null {"status":-70410}
May 03 08:10:16 hoobs hoobs[589]: 2021-05-03T06:10:16.483Z alexaActions alexaMessage: Response {
May 03 08:10:16 hoobs hoobs[589]: "event": {
May 03 08:10:16 hoobs hoobs[589]: "header": {
May 03 08:10:16 hoobs hoobs[589]: "namespace": "Alexa",
May 03 08:10:16 hoobs hoobs[589]: "name": "ErrorResponse",
May 03 08:10:16 hoobs hoobs[589]: "messageId": "f66317ec-698b-4179-ba78-6e2f58433342",
May 03 08:10:16 hoobs hoobs[589]: "correlationToken": "AAAAAAAAAQCJaTgJFuvl8NCbqOlfnXu5/AEAAAAAAADkWIaZOyIJJ5nWPkqCw5mwsS+4NeoHFbaA1sUCmbLQ67mSrVrfB+99PcWDq+uiIllt1rXFm0MimYgScJi5PvmjUreZvomhdK19r5MrjpLM7h15/XD7S4Yk7VnH/oJS8XBOH9qf0Wxl+8Tp5rk9nGwanrBhM1yHqjaWhTuhLzqRnbCT/K5nQvRGHyBWwdQlhIkXA8IbKXh4DqkGYJG3JyxD5ldEm/z17RNzNlBG5O16Pa+U2b5yyKYyDkUyYUgRwFwiW1MZMGRX1UDqTGLTsGIs8YCZ1kDMg+kBye1+pcyWhYQmJrrCGjK0jShdMn1M+RV87asq6qQKoAmB+i58m5poU90kBicHyvT2Cuu77CemwxQFbkGgH5+TJP1rpUNUpLnHgAGcofmEDAOv2HLdEd+COKYIp+LvZ4ZHWbqnQ6yLBSSjvS9lfuqnRx4kJfjucNDQUDucn6r8sm9NgGW8TGDCjy1+xv24RbzNv0zn2R4rvwZeoV++WeCmrIR99MA5bQTaaVeiRbWDPWPNgBNWlbtDjuFFslMg3JMjUo6niSwDf6dKaa0plVKXNks9dC6lpr+kTV0nEajdMbZw175rTWGtQh4XTquWRrTQ/7FsBzWZK/TDrrTe9EAmkvRmmQM7co1ATz3JmJXoglG7/2ODsYQ2VaNXo/ThTV4ROh+H",
May 03 08:10:16 hoobs hoobs[589]: "payloadVersion": "3"
May 03 08:10:16 hoobs hoobs[589]: },
May 03 08:10:16 hoobs hoobs[589]: "endpoint": {
May 03 08:10:16 hoobs hoobs[589]: "endpointId": "RDk6OUQ6NzI6RjQ6NkI6M0YtSE9PQlMtU2lnbmlmeSBOZXRoZXJsYW5kcyBCLlYuLVRpc2NobGFtcGUtMDAwMDAwNDMtMDAwMC0xMDAwLTgwMDAtMDAyNkJCNzY1Mjkx"
May 03 08:10:16 hoobs hoobs[589]: },
May 03 08:10:16 hoobs hoobs[589]: "payload": {
May 03 08:10:16 hoobs hoobs[589]: "type": "ENDPOINT_UNREACHABLE",
May 03 08:10:16 hoobs hoobs[589]: "message": "Homebridge status failed"
May 03 08:10:16 hoobs hoobs[589]: }
```

**Comment by RyTsYdUp** [comment]
I discovered this to be an issue in the latest version. I rolled back to 0.4.74 by uninstalling the plugin and issuing this command in the terminal "npm install -g homebridge-alexa@0.4.74". My Z-Wave devices now properly report their statuses but the Zigbee devices are still having issues. Alexa cannot receive updates from the Zigbee devices but they can still be controlled through Alexa.

**Comment by NorthernMan54** [comment]
As I don't have an implementation of HOOBS in my setup, I can not supply any support of these issues that appear to be triggered by the HOOBS implementation.  The current implementation on homebridge is extremely stable.

For these issues you should engage with the HOOBS team.

**Comment by RyTsYdUp** [comment]
> As I don't have an implementation of HOOBS in my setup, I can not supply any support of these issues that appear to be triggered by the HOOBS implementation. The current implementation on homebridge is extremely stable.
> 
> For these issues you should engage with the HOOBS team.

Hi NorthernMan,

First of all, thank you for this wonderful plugin. This is the one plugin that is most critical to my environment.

I'm running Homebridge and the issue is identical to Hoobs and was also seeing this error. Rolling back the plugin to 0.4.74 fixed the status updates to Alexa for z-wave devices, but zigbee devices still have the issue. Both z-wave and zigbee devices can be controlled, just not status updates in the Alexa app. The app says Device Unresponsive. 0.5+ makes this a problem for both z-wave and ZigBee devices.

I believe issues #432 and 435 are related.

**Comment by NorthernMan54** [comment]
Unfortunately the Alexa status updates cause DOS attacks on the cloud servers so it is expected to be problematic.

**Comment by NorthernMan54** [comment]
![9ACE383E-6807-419E-98AE-073E3A7E2CA1](https://user-images.githubusercontent.com/19808920/116893039-823cd600-abfe-11eb-8147-a83c58f305de.png)

**Comment by NorthernMan54** [comment]
The DOS attack
