### ISSUE TITLE
homebridge-alexa RangeError

### ISSUE THREAD

**Issue by jaydhary14** [NorthernMan54/homebridge-alexa#482]
I have homebridge running as a node on MacMini (Intel) 

I am getting below error 

[12/25/2021, 10:10:33 PM] RangeError: Maximum call stack size exceeded
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:30:5)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)
    at Function.Array.from (/usr/local/lib/node_modules/homebridge-alexa/node_modules/collections/shim-array.js:31:22)

**Comment by NorthernMan54** [comment]
Duplicate of #481
