### ISSUE TITLE
Errors in homebridge.log

### ISSUE THREAD

**Issue by sgtbobie** [NorthernMan54/homebridge-alexa#49]
Hey, 

I installed the NorthernMan54 version of homebridge and the homebridge-alexa plugin, but the plugin is not working and I see the following on the homebridge.log file.

[2018-1-31 11:12:22] ERROR LOADING PLUGIN homebridge-alexa:
[2018-1-31 11:12:22] Error: Cannot find module '/homebridge/node_modules/homebridge-alexa/index.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:72:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:145:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:141:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:58:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
[2018-1-31 11:12:22] ====================

Not sure what I am doing wrong. Can you help?

**Comment by NorthernMan54** [comment]
If you read the README, you will see that you don’t install the plugin, just the special version of homebridge.  To remove the plugin do this

sudo npm remove homebridge-alexa

**Comment by sgtbobie** [comment]
Oh, crap, I'm sorry. My head has been melted with work the last few days.
