### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by alexwala** [NorthernMan54/homebridge-alexa#508]
Got error - leads to restart of homebridge:
```
[3/23/2022, 7:08:55 AM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _sendHapEvent (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:102:24)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:69:11)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[3/23/2022, 7:08:55 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by NorthernMan54** [comment]
Well that obviously didn’t work

I will take another crack as this later today.

As these are messages from HomeKit devices aka homebridge, what version of homebridge are you running?

And are you running any other none native HomeKit devices?

**Comment by NorthernMan54** [comment]
Attempt # 2 is published at v0.5.58, and it should no longer trigger homebridge crashes.  It will also log a lot more detail when the same data condition occurs.

**Comment by alexwala** [comment]
thx !

**Comment by alexwala** [comment]
will there be a new version ?

**Comment by NorthernMan54** [comment]
Any repeats or log messages?

**Comment by alexwala** [comment]
```
[3/25/2022, 5:59:59 AM] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _sendHapEvent (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:102:24)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/hap-node-client/lib/eventedHttpClient.js:69:11)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by NorthernMan54** [comment]
It should no longer crash with 0.5.58 and will log details on the message received to further debug this

**Comment by alexwala** [comment]
hm currently i do not get any 0.5.58 version - only 0.5.56

**Comment by alexwala** [comment]
ok now there is a 0.5.60...will let you know if error occurs again- - thx

**Comment by NorthernMan54** [comment]
I just pushed 0.5.60 and 0.5.61 ( made a typo in CHANGELOG with 0.5.60 )

**Comment by alexwala** [comment]
thanks for the quick support !

**Comment by NorthernMan54** [comment]
No problem, I was doing other things this AM and needed to re-publish anyway. Not sure why 0.5.58 wasn’t listed

**Comment by alexwala** [comment]
got error again on main homebridge instance (192.168.0.100, homebridge-alex installed) :)
192.168.0.101 is another homebridge instance running on a RpiA (connected via wifi)

```
Error: _sendHapEvent Unexpected end of JSON input http://192.168.0.101:34653/characteristics {
  protocol: 'EVENT',
  httpVersion: 1,
  statusCode: 200,
  statusMessage: 'OK',
  method: null,
  url: 'http://192.168.0.101:34653/',
  headers: { 'Content-Type': 'application/hap+json', 'Content-Length': 50 },
  body: '{"characteristics":[{"aid":1,"ii',
  boundary: null,
  multipart: null,
  additional: ''
}
```

**Comment by alexwala** [comment]
No crash this time :)

I think the homebridge connected via wifi (192.168.0.101) do sometimes a reconnect:
`avahi-daemon[325]: Withdrawing address record for 192.168.0.101 on wlan0`

main homebridge (192.168.0.100):
```
System Information
Timezone	GMT+0100
OS		Raspbian GNU/Linux Buster (10)
Hostname	raspberrypi
IPv4 (eth0)	192.168.1.100
Node.js Version	v16.14.2
Npm Version	v8.5.0
User		pi
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Service Mode	Yes

multiple accessories/platforms
```
second homebridge (192.168.0.100):
```
System Information
Timezone	GMT+0100
OS		Raspbian GNU/Linux Buster (10)
Hostname	raspberrypi
IPv4 (eth0)	192.168.1.100
Node.js Version	v16.14.2
Npm Version	v8.5.0
User		pi
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Service Mode	Yes

2 accessories/platforms: raspberry_simple_gpio, Camera-ffmpeg
```

**Comment by NorthernMan54** [comment]
I have been trying to recreate this without any luck, any more error messages, hopefully that are a bit different
