### ISSUE TITLE
Recurring error that kills homebridge

### ISSUE THREAD

**Issue by JimBobSD** [NorthernMan54/homebridge-alexa#57]
First, love the plug-in.  Second, I am using he non-beta homebridge-alexa.  I keep having my homebridge instances die due to the following error.  I note that I do not have any hue capable lights:

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389
  var mac = hueDevices[lightid].uniqueid.split(':');
                               ^
TypeError: Cannot read property 'uniqueid' of undefined
    at _getAid (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389:32)
    at hueToHK (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:167:14)
    at Object.handleHueApi (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:55:24)
    at HAPServer._handleHueApi (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:875:7)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:214:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by NorthernMan54** [comment]
Have Alexa discover devices again, that should fix it.

**Comment by JimBobSD** [comment]
I removed all devices from Alexa Smart Home and then re-added them a couple of days ago.  Unfortunately, the error returned and killed homebridge:

/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389
  var mac = hueDevices[lightid].uniqueid.split(':');
                               ^
TypeError: Cannot read property 'uniqueid' of undefined
    at _getAid (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:389:32)
    at hueToHK (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:167:14)
    at Object.handleHueApi (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/hue.js:55:24)
    at HAPServer._handleHueApi (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:875:7)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:214:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by NorthernMan54** [comment]
@JimBobSD

What plugins are you using ?

What is happening is that Alexa and homebridge are getting out of whack for the address for devices.  When you do ‘Discover Devices’ I’m passing the device addresses to Alexa for all your accessories, and what is happening is that the device address are moving around in homebridge.  And this is not usual.  For me, my devices don’t change for months unless I add or delete devices.  Are you adding or deleting devices?

**Comment by JimBobSD** [comment]
I run six different instances of homebridge on a rasbperry pi.  This divides up my devices in case any particular homebridge instance crashes.  On this particular homebridge instance, I am running:

-homebridge-roomba-stv
-homebridge-pivot-power-genius

I have two pivot power genius ("PPG") power-strips (1 and 2), which has two controllable outlets on each strip (A and B).  This homebridge instance has 5 accessories on it: (1) Roomba, (2) PPG Outlet 1A, (3) PPG Outlet 1B, (4) PPG Outlet 2A, (5) PPG Outlet 2B.

I also had this error occur on a different instance of homebridge, but it has not repeated since I deleted all devices and re-added them to the Alexa app.

**Comment by NorthernMan54** [comment]
@JimBobSD Give me a day or 2 to put a wrapper around that error message to stop homebridge from exiting when it occurs.

**Comment by NorthernMan54** [comment]
Okay, I put a wrapper around the error.  It should stop crashing now.  Please reinstall and let me know how it goes.
