### ISSUE TITLE
Error while Installing

### ISSUE THREAD

**Issue by MeinMilchKaffee** [NorthernMan54/homebridge-alexa#63]
I get a bunch of errors while installing

with "_sudo npm install -g homebridge-alexa_"
I get "_gyp WARN EACCES user "root" does not have permission_"

with 
"_sudo su
sudo npm install -g —unsafe-perm homebridge-alexa_"
I get "_npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: [ '—unsafe-perm', 'homebridge-alexa' ]
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "—unsafe-perm": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-04T16_16_33_257Z-debug.log
root@raspberrypi:/home/pi#_ 
"

Debug Log:
"
_0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '—unsafe-perm',
1 verbose cli   'homebridge-alexa' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session e94fb6a94a3707c6
5 error arg Argument starts with non-ascii dash, this is probably invalid: [ '—unsafe-perm', 'homebridge-alexa' ]
6 silly install loadCurrentTree
7 silly install readGlobalPackageData
8 silly fetchPackageMetaData error for homebridge-alexa@latest install —unsafe-perm homebridge-alexa is not a legal HTTP header val$
9 verbose stack Error: Invalid tag name "—unsafe-perm": Tags may not have any characters that encodeURIComponent encodes.
9 verbose stack     at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:85:15)
9 verbose stack     at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:272:13)
9 verbose stack     at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:75:12)
9 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:48:10)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:204:14
9 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
9 verbose stack     at exports.getAllMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:201:3)
9 verbose stack     at Installer.loadArgMetadata (/usr/local/lib/node_modules/npm/lib/install.js:352:3)
9 verbose stack     at Installer.readGlobalPackageData (/usr/local/lib/node_modules/npm/lib/install.js:648:8)
9 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
9 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
9 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
10 verbose cwd /home/pi
11 verbose Linux 4.9.59-v7+
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "—unsafe-perm" "homebridge-alexa"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code EINVALIDTAGNAME
16 error Invalid tag name "—unsafe-perm": Tags may not have any characters that encodeURIComponent encodes.
17 verbose exit [ 1, true ]_
"

**Comment by MeinMilchKaffee** [comment]
OK with "sudo npm install -g —unsafe-perm homebridge-alexa" and without "sudo su" in the beginning it seems to work
