### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by nrushforth** [NorthernMan54/homebridge-alexa#67]
Hi, just installed and get the following when starting Homebridge with the -I option

 ====================
[2018-3-8 20:34:21] ERROR LOADING PLUGIN homebridge-alexa:
[2018-3-8 20:34:21] Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[2018-3-8 20:34:21] ====================

[2018-3-8 20:34:23] ---
[2018-3-8 20:34:23] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Alexa' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

Any ideas on what this could be?

**Comment by NorthernMan54** [comment]
This looks like the mdns module did not install correctly, can you reinstall with the unsafe-perm option.

sudo npm install -g —unsafe-perm homebridge-alexa
