### ISSUE TITLE
Alexa recconect 

### ISSUE THREAD

**Issue by wroblewski6** [NorthernMan54/homebridge-alexa#84]
Hi, 
I justed installed Alexa plugin but it does not work 

all the time it reconnect and I got 

ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.
  alexaLocal reconnect +5s

Please look at my log and tell me how to fix it. 

 alexaHAP Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +6ms
[2018-4-1 18:29:28] [Config] Console is listening on port 8080.
[2018-4-1 18:29:28] Homebridge is running on port 51823.
[2018-4-1 18:29:28] [Denon Switch ] do poll..
[2018-4-1 18:29:28] [Denon Adam Switch] do poll..
[2018-4-1 18:29:28] [Broadlink RM] Entertainment getSwitchState: false
[2018-4-1 18:29:28] [Broadlink RM] TV getSwitchState: true
[2018-4-1 18:29:28] [Broadlink RM] Projektor ON getSwitchState: false
[2018-4-1 18:29:28] [Broadlink RM] rolety down getSwitchState: true
[2018-4-1 18:29:28] [Broadlink RM] rolety up getSwitchState: false
[2018-4-1 18:29:28] [Broadlink RM] Volume Down getSwitchState: false
  alexaHAP HAP Device discovered TRADFRI gateway [ '192.168.1.23', 'fe80::deef:caff:febc:ee4f' ] +559ms
  alexaHAP HAP instance address: TRADFRI gateway -> TRADFRI-Gateway-dcefcabcee4f.local -> 192.168.1.23 +7ms
  alexaHAP HAP Device discovered Homebridge mac2 [ 'fe80::98:ba5e:c542:e17e', '192.168.1.26' ] +32ms
  alexaHAP HAP instance address: Homebridge mac2 -> MacBook-Krzysztof.local -> 192.168.1.26 +1ms
  alexaLocal offline +134ms
[2018-4-1 18:29:29] [Denon Adam Switch] current power state is: OFF
[2018-4-1 18:29:29] [Denon Adam Switch] poll end, state: false
Discovered Broadlink RM device at 192.168.1.13 (34:ea:34:88:f1:14)
[2018-4-1 18:29:29] [Denon Switch ] current power state is: ON
[2018-4-1 18:29:29] [Denon Switch ] poll end, state: true
  alexaHAP Homebridge instance discovered Homebridge mac2 with 11 accessories +140ms

**************************************************************************************************************
** Welcome to version 3.2.18 of the Homebridge Broadlink RM Plugin!

** Find out what's in the latest release here: https://github.com/lprhodes/homebridge-broadlink-rm/releases
** 
** If you like this plugin then please star it on GitHub or better yet buy me a drink using Paypal https://paypal.me/lprhodes or crypto https://goo.gl/bEn1RW.
** 
** Keep up to date with this plugin along with everything HomeKit and homebridge
** by signing up to my newsletter at http://workswith.io
**
** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
**
**************************************************************************************************************

  alexaHAP HAP Device discovered Homebridge Rpi2 [ 'fe80::ba27:ebff:fe91:b20f', '192.168.1.17' ] +316ms
  alexaHAP HAP instance address: Homebridge Rpi2 -> raspberrypi.local -> 192.168.1.17 +1ms
  alexaHAP Homebridge instance discovered Homebridge Rpi2 with 25 accessories +50ms
  alexaHAP HAP Discover failed TRADFRI gateway http://192.168.1.23:80 error code 470 +563ms
[UPDATE AVAILABLE] Version 3.5.5 of homebridge-broadlink-rm is available. The release notes can be found here: https://github.com/lprhodes/homebridge-broadlink-rm/releases/
  alexaLocal reconnect +4s
  alexaLocal connect command/wroblewski6/# +299ms
  alexaLocal offline +11s
  alexaLocal reconnect +5s
  alexaLocal reconnect +5s
  alexaLocal connect command/wroblewski6/# +412ms
  alexaLocal offline +11s
  alexaLocal reconnect +5s
  alexaLocal reconnect +5s
ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.
  alexaLocal connect command/wroblewski6/# +274ms
  alexaHAP Ending Homebridge instance discovery +6s
  alexaLocal offline +5s
[2018-4-1 18:30:28] [Denon Switch ] do poll..
[2018-4-1 18:30:28] [Denon Adam Switch] do poll..
[2018-4-1 18:30:28] [Denon Adam Switch] current power state is: OFF
[2018-4-1 18:30:28] [Denon Switch ] current power state is: ON
  alexaLocal reconnect +5s
  alexaLocal reconnect +5s
  alexaLocal connect command/wroblewski6/# +303ms
  alexaLocal offline +11s
  alexaLocal reconnect +5s
  alexaLocal reconnect +5s
  alexaLocal connect command/wroblewski6/# +410ms
  alexaLocal offline +11s
  alexaLocal reconnect +5s
ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.
  alexaLocal reconnect +5s
  alexaLocal connect command/wroblewski6/# +473ms
[2018-4-1 18:31:28] [Denon Switch ] do poll..
[2018-4-1 18:31:28] [Denon Adam Switch] do poll..
[2018-4-1 18:31:28] [Denon Switch ] current power state is: ON
[2018-4-1 18:31:28] [Denon Adam Switch] current power state is: OFF
  alexaLocal offline +11s
  alexaLocal reconnect +5s
  alexaLocal reconnect +5s
  alexaLocal connect command/wroblewski6/# +412ms
  alexaLocal offline +11s
  alexaLocal reconnect +5s

**Comment by NorthernMan54** [comment]
This error is caused by installing and configuring more than once.  It only needs to be installed once.

**Comment by wroblewski6** [comment]
so what I should do now to make it fix ??

**Comment by wroblewski6** [comment]
now I have error like this 

 alexaLocal Emitting alexa.powercontroller +6m
  alexaHAP Homebridge auth failed, invalid PIN 192.168.1.17:51823 {"characteristics":[{"aid":18,"iid":10,"value":1}]} null {"status":-70401} +20ms
[2018-4-1 21:37:43] [Alexa] PowerController TurnOn 192.168.1.17 51823 undefined Error: Homebridge auth failed, invalid PIN
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/alexaHAP.js:105:18)
    at Request._callback (/usr/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10042:25)
    at Request.requestRetryReply [as reply] (/usr/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  alexaLocal Emitting alexa.powercontroller +8s
  alexaHAP Homebridge auth failed, invalid PIN 192.168.1.17:51823 {"characteristics":[{"aid":18,"iid":10,"value":1}]} null {"status":-70401} +19ms
[2018-4-1 21:37:51] [Alexa] PowerController TurnOn 192.168.1.17 51823 undefined Error: Homebridge auth failed, invalid PIN
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/lib/alexaHAP.js:105:18)
    at Request._callback (/usr/lib/node_modules/homebridge-alexa/node_modules/lodash/lodash.js:10042:25)
    at Request.requestRetryReply [as reply] (/usr/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/requestretry/index.js:138:10)
    at Request.self.callback (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-alexa/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by NorthernMan54** [comment]
Looks like you are making progress,  for that error your need to set the PIN in the config if you had changed your config from the default.

https://github.com/NorthernMan54/homebridge-alexa#optional-parameters

**Comment by wroblewski6** [comment]
I manage to go even further and It works but only When i use Alexa app , When i use voice it does not work. What can be the reason ??

**Comment by wroblewski6** [comment]
I would love to troubleshoot on slack , can you invite me wroblewski6@gmail.com ?

**Comment by NorthernMan54** [comment]
The link for slack is here

https://github.com/nfarina/homebridge#community <https://github.com/nfarina/homebridge#community>

**Comment by wroblewski6** [comment]
I sign in on slack but not know how to chat with you, it is my first time on slack

**Comment by NorthernMan54** [comment]
I just sent a direct message

**Comment by Magutibasilio** [comment]
Hello, I have this error how do I solve it? Thank you

ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

**Comment by NorthernMan54** [comment]
Please open a new issue and include a DEBUG log.

This is a catch all error message that is triggered every 5 times that the MQTT connection to the www.homebridge.ca is reconnected.

If the message appears occasionally, it is okay but if it repeats it indicates an issue with the MQTT connection.

**Comment by Magutibasilio** [comment]
The truth is that I am very new and do not remove the debug from the container
marcoraddatz / homebridge: latest from qnap that I am using, since I do not know where it is stored.
