### ISSUE TITLE
ERROR: ETIMEDOUT

### ISSUE THREAD

**Issue by Mick93340** [NorthernMan54/homebridge-alexa#89]
Hi I had alexa and homebridge working perfectly all day and now can't have it running at all.

Here is the error when I ask for example : Alexa, Turn TV On.
=====================================================
[2018-4-10 01:08:43] [Alexa] PowerController TurnOff 192.168.1.142 51826 undefined { Error: ETIMEDOUT
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-alexa/node_modules/request/request.js:846:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
 code: 'ETIMEDOUT', connect: true, attempts: 1 }

Everything run fin on HomeKit.

Thanks for your help,

**Comment by NorthernMan54** [comment]
Try from the Alexa App, forgetting all the devices and discovering again.

**Comment by Mick93340** [comment]
Works like a charm now! Thx!
